CREATE TABLE IF NOT EXISTS services (id INTEGER PRIMARY KEY, category TEXT NOT NULL, name TEXT NOT NULL, minutes INTEGER NOT NULL, price INTEGER NOT NULL, active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS openings (id INTEGER PRIMARY KEY, day TEXT NOT NULL, start_min INTEGER NOT NULL, end_min INTEGER NOT NULL, CHECK(start_min < end_min));
CREATE INDEX IF NOT EXISTS openings_day ON openings(day);
CREATE TABLE IF NOT EXISTS clients (id INTEGER PRIMARY KEY, phone TEXT NOT NULL UNIQUE, name TEXT NOT NULL, note TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS bookings (id INTEGER PRIMARY KEY, day TEXT NOT NULL, start_min INTEGER NOT NULL, end_min INTEGER NOT NULL, service_id INTEGER NOT NULL, service_name TEXT NOT NULL, price INTEGER NOT NULL, client_name TEXT NOT NULL, phone TEXT NOT NULL, source TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'confirmed', created_at TEXT NOT NULL, client_id INTEGER, channel TEXT, channel_user_id TEXT);
CREATE INDEX IF NOT EXISTS bookings_day ON bookings(day,status);
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
INSERT OR IGNORE INTO settings (key,value) VALUES ('buffer_minutes','10'),('address',''),('contact','');
CREATE TABLE IF NOT EXISTS notifications (booking_id INTEGER NOT NULL, kind TEXT NOT NULL, sent_at TEXT NOT NULL, PRIMARY KEY(booking_id,kind));
CREATE TABLE IF NOT EXISTS daily_digests (day TEXT PRIMARY KEY, sent_at TEXT NOT NULL);
INSERT INTO services (category,name,minutes,price) VALUES ('Нарощування вій','Нарощування класичних вій (1D)',150,550);
INSERT INTO services (category,name,minutes,price) VALUES ('Нарощування вій','Нарощування вій об''єм 2D',150,550);
INSERT INTO services (category,name,minutes,price) VALUES ('Нарощування вій','Нарощування вій об''єм 3D',150,600);
INSERT INTO services (category,name,minutes,price) VALUES ('Нарощування вій','Нарощування вій 4D',150,600);
INSERT INTO services (category,name,minutes,price) VALUES ('Нарощування вій','Нарощування вій об''єм 5D',150,650);
INSERT INTO services (category,name,minutes,price) VALUES ('Нарощування вій','Нарощування вій 6D',160,650);
INSERT INTO services (category,name,minutes,price) VALUES ('Нарощування вій','Нарощування вій мега об’єм',165,750);
INSERT INTO services (category,name,minutes,price) VALUES ('Нарощування вій','Зняття вій',30,100);
INSERT INTO services (category,name,minutes,price) VALUES ('Ламінування вій','Ламінування вій + фарбування',75,450);
INSERT INTO services (category,name,minutes,price) VALUES ('Ламінування вій','Фарбування вій',15,100);
INSERT INTO services (category,name,minutes,price) VALUES ('Видалення волосся','Видалення волосся (зона обличчя)',20,100);
INSERT INTO services (category,name,minutes,price) VALUES ('Комплекси','Ламінування вій + видалення волосся',90,500);
INSERT INTO services (category,name,minutes,price) VALUES ('Комплекси','Ламінування вій та брів (ламінування + корекція + фарбування)',150,800);
INSERT INTO services (category,name,minutes,price) VALUES ('Комплекси','Ламінування вій та брів + видалення волосся',165,850);
INSERT INTO services (category,name,minutes,price) VALUES ('Оформлення брів','Корекція брів (пінцет + віск)',30,150);
INSERT INTO services (category,name,minutes,price) VALUES ('Оформлення брів','Фарбування брів (фарба або хна)',45,200);
INSERT INTO services (category,name,minutes,price) VALUES ('Оформлення брів','Корекція + фарбування брів',50,300);
INSERT INTO services (category,name,minutes,price) VALUES ('Оформлення брів','Ламінування брів',30,350);
INSERT INTO services (category,name,minutes,price) VALUES ('Оформлення брів','Ламінування брів + корекція',50,400);
INSERT INTO services (category,name,minutes,price) VALUES ('Оформлення брів','Ламінування брів + корекція + фарбування',60,500);
