 const TZ = 'Europe/Kyiv';
const encoder = new TextEncoder();
class Problem extends Error { constructor(message, status=400) { super(message); this.status=status; } }
const json = (value, status=200) => new Response(JSON.stringify(value), {status, headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}});
const ok = () => ({ok:true});
const one = (db, sql, ...args) => db.prepare(sql).bind(...args).first();
const all = async (db, sql, ...args) => (await db.prepare(sql).bind(...args).all()).results;
const pad = n => String(n).padStart(2,'0');
const fmt = n => `${pad(Math.floor(n/60))}:${pad(n%60)}`;
const phoneKey = v => {let d=String(v||'').replace(/\D/g,'');if(d.startsWith('380')&&d.length===12)return d;if(d.startsWith('0')&&d.length===10)return '38'+d;return d};
const today = () => new Intl.DateTimeFormat('sv-SE',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const nowMinute = () => {const parts=new Intl.DateTimeFormat('en-GB',{timeZone:TZ,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date());return Number(parts.find(x=>x.type==='hour').value)*60+Number(parts.find(x=>x.type==='minute').value)};
const plusDays = (day,n) => new Date(Date.parse(day+'T12:00:00Z')+n*86400000).toISOString().slice(0,10);
function day(value, future=true){if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value)||Number.isNaN(Date.parse(value+'T12:00:00Z'))||new Date(value+'T12:00:00Z').toISOString().slice(0,10)!==value)throw new Problem('Невірна дата');if(future&&(value<today()||value>plusDays(today(),90)))throw new Problem('Оберіть дату в межах наступних 90 днів');return value}
function minute(v){if(typeof v!=='string'||!/^([01]\d|2[0-3]):[0-5]\d$/.test(v))throw new Problem('Вкажіть час у форматі ГГ:ХХ');return Number(v.slice(0,2))*60+Number(v.slice(3))}
function required(v,label,max){if(typeof v!=='string'||!v.trim()||v.trim().length>max)throw new Problem(`Перевірте поле «${label}»`);return v.trim()}
const nint = v => Number.isInteger(Number(v)) ? Number(v) : NaN;
const secretEq = (a,b) => {if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0};
const hmac = async (key,data) => new Uint8Array(await crypto.subtle.sign('HMAC',await crypto.subtle.importKey('raw',key,{name:'HMAC',hash:'SHA-256'},false,['sign']),encoder.encode(data)));
const hex = bytes => Array.from(bytes).map(x=>x.toString(16).padStart(2,'0')).join('');
const icsText = v => String(v).replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');
function foldIcsLine(line){let parts=[''],length=0;for(const char of line){const size=encoder.encode(char).length;if(length+size>75){parts.push(' ');length=1}parts[parts.length-1]+=char;length+=size}return parts.join('\r\n')}
function calendarFeed(bookings){const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Online Zapys//Booking Calendar//UK','CALSCALE:GREGORIAN','X-WR-CALNAME:Мої записи','X-WR-TIMEZONE:Europe/Kyiv'];for(const b of bookings){const stamp=b.day.replaceAll('-',''),at=n=>`${stamp}T${pad(Math.floor(n/60))}${pad(n%60)}00`,name=String(b.client_name||'').trim(),contact=String(b.contact_value||b.phone||'').trim(),type=String(b.contact_type||'Телефон').trim(),note=String(b.client_note||'').trim();const details=[`Клієнт: ${name||'Не вказано'}`,contact?`${type}: ${contact}`:'',b.status==='completed'?'Візит завершено':'',note?`Нотатка: ${note}`:''].filter(Boolean).join('\n');lines.push('BEGIN:VEVENT',`UID:booking-${b.id}@online-zapys`,`DTSTAMP:${new Date(b.created_at).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}`,`DTSTART;TZID=Europe/Kyiv:${at(b.start_min)}`,`DTEND;TZID=Europe/Kyiv:${at(b.end_min)}`,`SUMMARY:${icsText(b.service_name)}`,`DESCRIPTION:${icsText(details)}`,'END:VEVENT')}lines.push('END:VCALENDAR');return lines.map(foldIcsLine).join('\r\n')+'\r\n'}
async function tgIdentity(raw,env){if(!env.TELEGRAM_BOT_TOKEN||!raw||raw.length>4096)throw new Problem('Немає даних Telegram',401);const p=new URLSearchParams(raw),signature=p.get('hash');p.delete('hash');const check=[...p.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join('\n');const key=await hmac(encoder.encode('WebAppData'),env.TELEGRAM_BOT_TOKEN);if(!secretEq(signature,hex(await hmac(key,check))))throw new Problem('Неправильний підпис Telegram',401);let u;try{u=JSON.parse(p.get('user'));if(!Number.isInteger(Number(u.id))||Math.abs(Date.now()/1000-Number(p.get('auth_date')))>86400)throw Error()}catch{throw new Problem('Сесія Telegram застаріла',401)}return String(u.id)}
async function admin(req,env){if(env.BOOKING_ADMIN_KEY?.length<16)throw new Problem('Адмінключ не налаштований',500);if(secretEq(req.headers.get('x-admin-key'),env.BOOKING_ADMIN_KEY))return;try{if(env.ADMIN_TELEGRAM_ID&&await tgIdentity(req.headers.get('x-telegram-init-data'),env)===env.ADMIN_TELEGRAM_ID)return}catch{}throw new Problem('Потрібен доступ майстра',403)}
async function body(req){let str=await req.text();if(str.length>16384)throw new Problem('Завеликий запит');try{const v=JSON.parse(str);if(v&&typeof v==='object'&&!Array.isArray(v))return v}catch{}throw new Problem('Некоректні дані запиту')}
async function settings(db){return Object.fromEntries((await all(db,'SELECT key,value FROM settings')).map(x=>[x.key,x.value]))}
const weekday=d=>new Date(`${d}T12:00:00Z`).getUTCDay();
async function weeklyTemplate(db){const row=await one(db,"SELECT value FROM settings WHERE key='weekly_hours'");return row?JSON.parse(row.value):{}}
async function effectiveOpenings(db,d){const [specific,off,weekly]=await Promise.all([all(db,'SELECT start_min,end_min FROM openings WHERE day=? ORDER BY start_min',d),one(db,'SELECT 1 FROM settings WHERE key=?',`day_off:${d}`),weeklyTemplate(db)]);return {windows:off?[]:specific.length?specific:weekly[weekday(d)]||[],source:off?'day_off':specific.length?'custom':weekly[weekday(d)]?.length?'weekly':'unset'}}
async function configuredDays(db,from,to){const [explicit,off,weekly]=await Promise.all([all(db,'SELECT DISTINCT day FROM openings WHERE day>=? AND day<=?',from,to),all(db,"SELECT substr(key,9) day FROM settings WHERE key>=? AND key<=? AND value='1'",`day_off:${from}`,`day_off:${to}`),weeklyTemplate(db)]);const dates=new Set(explicit.map(x=>x.day)),closed=new Set(off.map(x=>x.day));for(let d=from;d<=to;d=plusDays(d,1))if(!closed.has(d)&&weekly[weekday(d)]?.length)dates.add(d);return [...dates].filter(d=>!closed.has(d)).sort()}
const openingSQL=`(EXISTS(SELECT 1 FROM openings WHERE day=? AND start_min<=? AND end_min>=?) OR (NOT EXISTS(SELECT 1 FROM openings WHERE day=?) AND NOT EXISTS(SELECT 1 FROM settings WHERE key=?) AND EXISTS(SELECT 1 FROM settings s,json_each(s.value,'$."'||strftime('%w',?)||'"') j WHERE s.key='weekly_hours' AND CAST(json_extract(j.value,'$.start_min') AS INTEGER)<=? AND CAST(json_extract(j.value,'$.end_min') AS INTEGER)>=?)))`;
const openingArgs=(d,start,end)=>[d,start,end,d,`day_off:${d}`,d,start,end];
async function available(db,d,duration,exclude=-1){const [schedule,bookings,setting,busySetting]=await Promise.all([effectiveOpenings(db,d),all(db,"SELECT id,start_min,end_min FROM bookings WHERE day=? AND status='confirmed' AND id!=?",d,exclude),one(db,"SELECT value FROM settings WHERE key='buffer_minutes'"),one(db,'SELECT value FROM settings WHERE key=?',`busy:${d}`)]);const buffer=Number(setting?.value||10),busy=JSON.parse(busySetting?.value||'[]'),out=new Set();for(const w of schedule.windows){for(let pos=Math.ceil(w.start_min/5)*5;pos+duration<=w.end_min;pos+=5){if(d===today()&&pos<=nowMinute())continue;if(bookings.every(b=>pos>=b.end_min+buffer||pos+duration+buffer<=b.start_min)&&busy.every(b=>pos>=b.end+buffer||pos+duration+buffer<=b.start))out.add(fmt(pos))}}return [...out].sort()}
async function telegramApi(env,method,payload){if(!env.TELEGRAM_BOT_TOKEN)throw Error('Telegram token missing');const response=await fetch(`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const result=await response.json();if(!result.ok)throw Error(`Telegram ${method}: ${result.description||response.status}`);return result.result}
async function sendTelegram(env,recipient,text,markup){return telegramApi(env,'sendMessage',{chat_id:recipient,text,...(markup?{reply_markup:markup}:{})})}
async function notify(env,b,kind){if(b?.channel==='telegram'&&b.channel_user_id)await sendTelegram(env,b.channel_user_id,`${{created:'Ваш запис підтверджено',moved:'Ваш запис перенесено',cancelled:'Ваш запис скасовано'}[kind]} 🩷\n${b.day} о ${fmt(b.start_min)}\n${b.service_name}`,{remove_keyboard:true})}
async function notifyMaster(env,b,kind){const chat=env.TELEGRAM_ADMIN_CHAT_ID||env.ADMIN_TELEGRAM_ID;if(!chat)return;const clean=v=>String(v||'').replace(/[\r\n]+/g,' ').trim();const contact=clean(b.contact_value||b.phone)||'не вказано';const title=kind==='created'?'🆕 Новий запис':kind==='cancelledByMaster'?'❌ Запис скасовано майстром':'❌ Клієнт скасував запис';const origin=b.source==='manual'?' · вручну':'';await sendTelegram(env,chat,`${title}${origin}\n${b.day} о ${fmt(b.start_min)}\n${clean(b.service_name)}\n${clean(b.client_name)||'Без імені'}\n${clean(b.contact_type)||'Контакт'}: ${contact}`)}
function queueMasterNotice(ctx,env,b,kind){ctx.waitUntil(notifyMaster(env,b,kind).catch(error=>console.error('Master Telegram notification failed',error)))}
async function booking(db,env,data,manual,ctx,trustedTelegramUser=null){const d=day(data.day),start=minute(data.time);let ids=Array.isArray(data.service_ids)?data.service_ids.map(nint).filter(Number.isInteger):[nint(data.service_id)];ids=[...new Set(ids)];if(!ids.length||ids.length>12)throw new Problem('Оберіть послугу');let name=String(data.name||'').trim(),phone=String(data.phone||'').trim();if(name.length>80||phone.length>60)throw new Problem('Перевірте контактні дані');const contactType=String(data.contact_type||'Телефон').trim()||'Телефон';const contactValue=String(data.contact_value||phone).trim();if(!manual&&!contactValue)throw new Problem('Вкажіть контакт клієнта');if(!['Телефон','Instagram','Telegram','Без контакту'].includes(contactType)||!manual&&contactType==='Без контакту')throw new Problem('Оберіть тип контакту');if(contactValue&&contactType==='Телефон'&&!/^\+?[0-9 ()-]{9,30}$/.test(contactValue))throw new Problem('Перевірте номер телефону');if(!name)name='Без імені';if(!phone)phone=contactType==='Телефон'?contactValue:'';const marks=ids.map(()=>'?').join(',');const services=await all(db,`SELECT * FROM services WHERE active=1 AND id IN (${marks})`,...ids);if(services.length!==ids.length)throw new Problem('Одна з послуг вже недоступна',409);const service=services[0],duration=services.reduce((sum,s)=>sum+s.minutes,0),totalPrice=services.reduce((sum,s)=>sum+s.price,0),serviceName=services.map(s=>s.name).join(' + ');let channel=null,user=null;if(!manual&&trustedTelegramUser){user=String(trustedTelegramUser);channel='telegram'}else if(!manual&&data.telegram_init_data){user=await tgIdentity(data.telegram_init_data,env);channel='telegram'}let source=manual?'manual':channel||data.source;if(!['web','telegram','instagram','viber','manual'].includes(source))source='web';
  if(!manual&&!user&&contactType==='Телефон'&&contactValue){const profiles=await all(db,'SELECT user_id,phone FROM telegram_profiles');const linked=profiles.find(p=>phoneKey(p.phone)===phoneKey(contactValue));if(linked){user=String(linked.user_id);channel='telegram'}}
  if(!manual&&(start%5||d===today()&&start<=nowMinute()))throw new Problem('Оберіть доступний час',409);
  if(manual&&start+duration>1440)throw new Problem('Послуга має завершитися до кінця вибраного дня');
  // The availability and overlap checks belong to one atomic INSERT statement.
  const clientKey=contactValue?`${contactType}:${contactValue}`:`anon-${crypto.randomUUID()}`;await db.prepare('INSERT INTO clients(phone,name,contact_type,contact_value) VALUES (?,?,?,?) ON CONFLICT(phone) DO UPDATE SET name=excluded.name,contact_type=excluded.contact_type,contact_value=excluded.contact_value').bind(clientKey,name,contactType,contactValue).run();
  const client=await one(db,'SELECT id FROM clients WHERE phone=?',clientKey);
  const bookingValues=[d,start,start+duration,service.id,serviceName,totalPrice,name,phone,source,new Date().toISOString(),client.id,channel,user,contactType,contactValue];
  let result;
  if(manual){
    result=await db.prepare(`INSERT INTO bookings(day,start_min,end_min,service_id,service_name,price,client_name,phone,source,created_at,client_id,channel,channel_user_id,contact_type,contact_value)
    VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(...bookingValues).run();
  }else{
    const buffer=Number((await one(db,"SELECT value FROM settings WHERE key='buffer_minutes'"))?.value||10);
    result=await db.prepare(`INSERT INTO bookings(day,start_min,end_min,service_id,service_name,price,client_name,phone,source,created_at,client_id,channel,channel_user_id,contact_type,contact_value)
    SELECT ?,?,?,?,?,?,?,?,?,?,?,?,?,?,? WHERE ${openingSQL}
    AND NOT EXISTS(SELECT 1 FROM bookings WHERE day=? AND status='confirmed' AND NOT (? >= end_min+? OR ?+?+? <= start_min))
    AND NOT EXISTS(SELECT 1 FROM settings s, json_each(s.value) j WHERE s.key=? AND NOT (? >= CAST(json_extract(j.value,'$.end') AS INTEGER)+? OR ?+?+? <= CAST(json_extract(j.value,'$.start') AS INTEGER)))`).bind(...bookingValues,...openingArgs(d,start,start+duration),d,start,buffer,start,duration,buffer,`busy:${d}`,start,buffer,start,duration,buffer).run();
  }
  if(!result.meta.changes)throw new Problem('Цей час уже зайнятий або недоступний. Оберіть інший.',409);
  const b=await one(db,'SELECT * FROM bookings WHERE id=?',result.meta.last_row_id);queueMasterNotice(ctx,env,b,'created');if(channel)ctx.waitUntil(notify(env,b,'created'));return {id:b.id,day:d,start:fmt(start),end:fmt(b.end_min),service:b.service_name,price:b.price}}
async function move(db,env,id,data,ctx){const d=day(data.day),start=minute(data.time);if(start%5||d===today()&&start<=nowMinute())throw new Problem('Оберіть доступний час',409);const b=await one(db,"SELECT * FROM bookings WHERE id=? AND status='confirmed'",id);if(!b)throw new Problem('Запис не знайдено',404);const duration=b.end_min-b.start_min,buffer=Number((await one(db,"SELECT value FROM settings WHERE key='buffer_minutes'"))?.value||10);const result=await db.prepare(`UPDATE bookings SET day=?,start_min=?,end_min=? WHERE id=? AND status='confirmed'
 AND ${openingSQL}
 AND NOT EXISTS(SELECT 1 FROM bookings other WHERE other.day=? AND other.status='confirmed' AND other.id!=? AND NOT (? >= other.end_min+? OR ?+?+?<=other.start_min))
 AND NOT EXISTS(SELECT 1 FROM settings s, json_each(s.value) j WHERE s.key=? AND NOT (? >= CAST(json_extract(j.value,'$.end') AS INTEGER)+? OR ?+?+? <= CAST(json_extract(j.value,'$.start') AS INTEGER)))`).bind(d,start,start+duration,id,...openingArgs(d,start,start+duration),d,id,start,buffer,start,duration,buffer,`busy:${d}`,start,buffer,start,duration,buffer).run();if(!result.meta.changes)throw new Problem('Новий час зайнятий або недоступний',409);await db.prepare('DELETE FROM notifications WHERE booking_id=?').bind(id).run();ctx.waitUntil(notify(env,{...b,day:d,start_min:start},'moved'));return {ok:true,day:d,start:fmt(start)}}
async function editBooking(db,env,id,data,ctx){const previous=await one(db,"SELECT * FROM bookings WHERE id=? AND status IN ('confirmed','completed')",id);if(!previous)throw new Problem('Запис не знайдено',404);const d=day(data.day,false),start=minute(data.time),name=required(data.name,'Ім’я',80);let serviceId=previous.service_id,serviceName=previous.service_name,price=previous.price,duration=previous.end_min-previous.start_min;if(data.service_id){const service=await one(db,'SELECT id,name,minutes,price FROM services WHERE id=? AND active=1',nint(data.service_id));if(!service)throw new Problem('Послугу не знайдено',404);serviceId=service.id;serviceName=service.name;price=service.price;duration=service.minutes}if(start+duration>1440)throw new Problem('Послуга має завершитися до кінця дня');if(previous.status==='completed'&&d>today())throw new Problem('Завершений візит не може бути в майбутньому');const result=await db.prepare("UPDATE bookings SET day=?,start_min=?,end_min=?,service_id=?,service_name=?,price=?,client_name=? WHERE id=? AND status IN ('confirmed','completed')").bind(d,start,start+duration,serviceId,serviceName,price,name,id).run();if(!result.meta.changes)throw new Problem('Запис уже змінено',409);if(previous.client_id&&name!==previous.client_name)await db.prepare('UPDATE clients SET name=? WHERE id=? AND name=?').bind(name,previous.client_id,previous.client_name).run();if(previous.status==='confirmed'&&(d!==previous.day||start!==previous.start_min||serviceName!==previous.service_name)){await db.prepare('DELETE FROM notifications WHERE booking_id=?').bind(id).run();if(previous.channel==='telegram'&&previous.channel_user_id)ctx.waitUntil(notify(env,{...previous,day:d,start_min:start,service_name:serviceName},'moved').catch(error=>console.error('Booking edit notification failed',error)))}return json(ok())}
const keyboard = rows => ({inline_keyboard:rows});
const btn = (text,data) => ({text,callback_data:data});
const contactKeyboard = () => ({keyboard:[[{text:'Поділитися контактом',request_contact:true}],[{text:'Ввести вручну'}]],resize_keyboard:true,one_time_keyboard:true});
async function chatSession(db,user){return one(db,'SELECT * FROM telegram_chat_sessions WHERE user_id=?',user)}
async function saveChat(db,user,stage,values={}){const s={...(await chatSession(db,user)),...values};await db.prepare(`INSERT INTO telegram_chat_sessions(user_id,stage,category,service_id,day,time,name,phone,service_ids,updated_at)
 VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET stage=excluded.stage,category=excluded.category,service_id=excluded.service_id,day=excluded.day,time=excluded.time,name=excluded.name,phone=excluded.phone,service_ids=excluded.service_ids,updated_at=excluded.updated_at`).bind(user,stage,s.category??null,s.service_id??null,s.day??null,s.time??null,s.name??null,s.phone??null,s.service_ids??'[]',new Date().toISOString()).run()}
function chosenIds(session){try{const ids=JSON.parse(session?.service_ids||'[]');return Array.isArray(ids)?ids.filter(Number.isInteger).slice(0,12):[]}catch{return []}}
async function chosenServices(db,session){const ids=chosenIds(session);if(!ids.length&&session?.service_id)ids.push(session.service_id);if(!ids.length)return [];const rows=await all(db,`SELECT * FROM services WHERE active=1 AND id IN (${ids.map(()=>'?').join(',')})`,...ids);return rows.length===ids.length?rows:[]}
async function chatServices(db,env,user,reset=true){const categories=await all(db,'SELECT DISTINCT category FROM services WHERE active=1 ORDER BY category');if(!categories.length)return sendTelegram(env,user,'Зараз немає доступних послуг. Спробуйте пізніше.');await saveChat(db,user,'category',reset?{category:null,service_id:null,service_ids:'[]',day:null,time:null,name:null,phone:null}:{category:null,day:null,time:null});const count=chosenIds(await chatSession(db,user)).length,rows=categories.map((x,i)=>[btn(x.category,`cat:${i}`)]);if(count)rows.push([btn(`✅ Готово · ${count} послуг`,`done_services`)]);rows.push([btn('Скасувати','stop')]);return sendTelegram(env,user,'Оберіть категорію послуг:',keyboard(rows))}
async function chatCategory(db,env,user,category){const s=await chatSession(db,user),services=await all(db,'SELECT id,name,minutes,price FROM services WHERE category=? AND active=1 ORDER BY id',category),chosen=chosenIds(s);await saveChat(db,user,'service',{category});const rows=services.map(x=>[btn(`${chosen.includes(x.id)?'✓ ':''}${x.name.slice(0,37)} · ${x.price} ₴`,`svc:${x.id}`)]);if(chosen.length)rows.push([btn(`✅ Готово · ${chosen.length} послуг`,'done_services')]);rows.push([btn('← Категорії','categories')]);return sendTelegram(env,user,`Категорія: ${category}\nМожна вибрати кілька послуг:`,keyboard(rows))}
async function chatDays(db,env,user,offset=0){const s=await chatSession(db,user),services=await chosenServices(db,s);if(!services.length)return chatServices(db,env,user);const duration=services.reduce((n,x)=>n+x.minutes,0),price=services.reduce((n,x)=>n+x.price,0);const dates=await configuredDays(db,today(),plusDays(today(),90));const page=dates.slice(offset,offset+7),rows=[];for(const d of page){if((await available(db,d,duration)).length)rows.push([btn(d,`day:${d}`)])}if(offset+7<dates.length)rows.push([btn('Наступні дні →',`days:${offset+7}`)]);if(offset)rows.push([btn('← Попередні дні',`days:${Math.max(0,offset-7)}`)]);rows.push([btn('← Послуги','categories')]);await saveChat(db,user,'day',{day:null,time:null});return sendTelegram(env,user,`${services.map(x=>x.name).join(' + ')} · ${duration} хв · ${price} ₴\nОберіть дату${page.length&&!rows.some(r=>r[0].callback_data.startsWith('day:'))?' (на цій сторінці вільних годин немає)':''}:`,keyboard(rows))}
async function chatTimes(db,env,user,offset=0){const s=await chatSession(db,user),services=await chosenServices(db,s);if(!services.length||!s?.day)return chatServices(db,env,user);const slots=await available(db,day(s.day),services.reduce((n,x)=>n+x.minutes,0)),rows=[];for(let i=offset;i<Math.min(offset+8,slots.length);i+=2)rows.push(slots.slice(i,i+2).map(t=>btn(t,`time:${t}`)));const nav=[];if(offset)nav.push(btn('←',`times:${Math.max(0,offset-8)}`));if(offset+8<slots.length)nav.push(btn('→',`times:${offset+8}`));if(nav.length)rows.push(nav);rows.push([btn('← Дати','days:0')]);await saveChat(db,user,'time',{time:null});return sendTelegram(env,user,`Дата: ${s.day}. ${slots.length?'Оберіть вільний час:':'Вільного часу немає, оберіть іншу дату.'}`,keyboard(rows))}
async function handleTelegram(update,env,ctx){const db=env.DB,callback=update.callback_query,message=update.message,chat=callback?.message?.chat||message?.chat;if(chat?.type!=='private')return;const user=String(callback?.from?.id??message?.from?.id??'');if(!user||user!==String(chat.id))return;if(callback)await telegramApi(env,'answerCallbackQuery',{callback_query_id:callback.id});const data=callback?.data||'',text=message?.text?.trim(),s=await chatSession(db,user);
  if(text==='/id')return sendTelegram(env,user,`Ваш Telegram ID: ${user}`);
  if(text?.startsWith('/start connect')){await saveChat(db,user,'link_contact',{category:null,service_id:null,service_ids:'[]',day:null,time:null,name:null,phone:null});return sendTelegram(env,user,'Підключіть свій номер до записів. Telegram передасть боту номер лише після вашого натискання кнопки нижче.',contactKeyboard())}
  if(text?.startsWith('/start')||text==='/cancel'||data==='stop'||data==='home'){await saveChat(db,user,'idle',{category:null,service_id:null,service_ids:'[]',day:null,time:null,name:null,phone:null});return sendTelegram(env,user,'Вітаємо! Тут можна записатися прямо в чаті 🩷',keyboard([[btn('📅 Записатися','book')],[btn('Мої записи','mine')],[btn('📍 Адреса','address'),btn('📷 Instagram','instagram')]]))}
  if(text==='/address'||data==='address'){const address=(await one(db,"SELECT value FROM settings WHERE key='address'"))?.value?.trim()||'Лазаряна 3А, Дніпро';return sendTelegram(env,user,`📍 Адреса: ${address}`,keyboard([[btn('← Головне меню','home')]]))}
  if(text==='/instagram'||data==='instagram'){const saved=(await one(db,"SELECT value FROM settings WHERE key='instagram'"))?.value?.trim()||'@angelina_lashes.dp';const handle=saved.replace(/^@/,'');const url=/^https:\/\/(?:www\.)?instagram\.com\/[A-Za-z0-9._]+\/?(?:\?.*)?$/i.test(saved)?saved:/^[A-Za-z0-9._]+$/.test(handle)?`https://www.instagram.com/${handle}/`:null;return sendTelegram(env,user,`📷 Instagram: ${saved}`,keyboard([...(url?[[{text:'Відкрити Instagram',url}]]:[]),[btn('← Головне меню','home')]]))}
  if(text==='/book'||data==='book')return chatServices(db,env,user);
  if(data==='categories'&&['service','day'].includes(s?.stage))return chatServices(db,env,user,false);
  if(text==='/mybookings'||data==='mine'){const rows=await all(db,"SELECT id,day,start_min,service_name FROM bookings WHERE channel='telegram' AND channel_user_id=? AND status='confirmed' AND day>=? ORDER BY day,start_min LIMIT 10",user,today());if(!rows.length)return sendTelegram(env,user,'Майбутніх записів немає.',keyboard([[btn('📅 Новий запис','book')]]));const buttons=rows.map(b=>[btn(`❌ Скасувати ${b.day} ${fmt(b.start_min)}`,`cancel_booking:${b.id}`)]);buttons.push([btn('📅 Новий запис','book')]);return sendTelegram(env,user,'Ваші найближчі записи:\n'+rows.map(x=>`${x.day} о ${fmt(x.start_min)} — ${x.service_name}`).join('\n'),keyboard(buttons))}
  if(data.startsWith('cancel_booking:')){const id=nint(data.slice('cancel_booking:'.length)),b=await one(db,"SELECT * FROM bookings WHERE id=? AND channel='telegram' AND channel_user_id=? AND status='confirmed'",id,user);if(!b)return sendTelegram(env,user,'Запис уже скасовано або його не знайдено.',keyboard([[btn('Мої записи','mine')]]));return sendTelegram(env,user,`Скасувати запис?\n\n${b.day} о ${fmt(b.start_min)}\n${b.service_name}`,keyboard([[btn('❌ Так, скасувати',`confirm_cancel:${b.id}`)],[btn('← Ні, залишити','mine')]]))}
  if(data.startsWith('confirm_cancel:')){const id=nint(data.slice('confirm_cancel:'.length)),b=await one(db,"SELECT * FROM bookings WHERE id=? AND channel='telegram' AND channel_user_id=? AND status='confirmed'",id,user);if(!b)return sendTelegram(env,user,'Запис уже скасовано або його не знайдено.',keyboard([[btn('Мої записи','mine')]]));const result=await db.prepare("UPDATE bookings SET status='cancelled' WHERE id=? AND channel='telegram' AND channel_user_id=? AND status='confirmed'").bind(id,user).run();if(!result.meta.changes)return sendTelegram(env,user,'Не вдалося скасувати запис.',keyboard([[btn('Мої записи','mine')]]));queueMasterNotice(ctx,env,b,'cancelled');return sendTelegram(env,user,`Запис скасовано ✅\n\n${b.day} о ${fmt(b.start_min)}\n${b.service_name}`,keyboard([[btn('Мої записи','mine')],[btn('📅 Новий запис','book')]]))}
  if(data.startsWith('cat:')&&s?.stage==='category'){const categories=await all(db,'SELECT DISTINCT category FROM services WHERE active=1 ORDER BY category'),category=categories[nint(data.slice(4))]?.category;if(!category)return chatServices(db,env,user,false);return chatCategory(db,env,user,category)}
  if(data.startsWith('svc:')&&s?.stage==='service'){const service=await one(db,'SELECT id FROM services WHERE id=? AND category=? AND active=1',nint(data.slice(4)),s.category);if(!service)return chatServices(db,env,user,false);const ids=chosenIds(s),index=ids.indexOf(service.id);if(index>=0)ids.splice(index,1);else if(ids.length<12)ids.push(service.id);await saveChat(db,user,'service',{service_ids:JSON.stringify(ids),service_id:ids[0]??null});return chatCategory(db,env,user,s.category)}
  if(data==='done_services'&&['category','service'].includes(s?.stage)){if(!(await chosenServices(db,s)).length)return chatServices(db,env,user,false);await saveChat(db,user,'day');return chatDays(db,env,user)}
  if(data.startsWith('days:')&&['day','time'].includes(s?.stage)){const offset=nint(data.slice(5));if(offset>=0&&offset<=90)return chatDays(db,env,user,offset)}
  if(data.startsWith('day:')&&s?.stage==='day'){const d=day(data.slice(4)),services=await chosenServices(db,s);if(services.length&&(await available(db,d,services.reduce((n,x)=>n+x.minutes,0))).length){await saveChat(db,user,'time',{day:d});return chatTimes(db,env,user)}return chatDays(db,env,user)}
  if(data.startsWith('times:')&&s?.stage==='time'){const offset=nint(data.slice(6));if(offset>=0&&offset<200)return chatTimes(db,env,user,offset)}
  if(data.startsWith('time:')&&s?.stage==='time'){const time=data.slice(5),services=await chosenServices(db,s),duration=services.reduce((n,x)=>n+x.minutes,0);if(services.length&&(await available(db,s.day,duration)).includes(time)){const profile=await one(db,'SELECT name,phone FROM telegram_profiles WHERE user_id=?',user);if(profile?.name&&profile?.phone){await saveChat(db,user,'confirm',{time,name:profile.name,phone:profile.phone});return sendTelegram(env,user,`Перевірте запис:\n${services.map(x=>x.name).join(' + ')} · ${services.reduce((n,x)=>n+x.price,0)} ₴\n${s.day} о ${time}\n${profile.name} · ${profile.phone}`,keyboard([[btn('✅ Підтвердити','confirm')],[btn('Змінити контакт','change_contact')],[btn('Скасувати','stop')]]))}await saveChat(db,user,'contact',{time});return sendTelegram(env,user,'Хочете поділитися контактом, щоб не вводити ім’я та номер щоразу?',contactKeyboard())}return chatTimes(db,env,user)}
  if(s?.stage==='link_contact'&&message?.contact){if(String(message.contact.user_id||'')!==user)return sendTelegram(env,user,'Поділіться, будь ласка, власним контактом.',contactKeyboard());const phone=String(message.contact.phone_number||'').trim();if(!/^\+?[0-9 ()-]{9,30}$/.test(phone))return sendTelegram(env,user,'Не вдалося прочитати номер. Спробуйте ще раз.',contactKeyboard());const name=String(message.contact.first_name||message.from?.first_name||'Без імені').slice(0,80);await db.prepare('INSERT INTO telegram_profiles(user_id,name,phone,updated_at) VALUES (?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET name=excluded.name,phone=excluded.phone,updated_at=excluded.updated_at').bind(user,name,phone,new Date().toISOString()).run();const rows=await all(db,"SELECT id,day,start_min,service_name,contact_value,phone FROM bookings WHERE status='confirmed' AND day>=?",today());const matches=rows.filter(b=>phoneKey(b.contact_value||b.phone)===phoneKey(phone));for(const b of matches)await db.prepare('UPDATE bookings SET channel=?,channel_user_id=? WHERE id=?').bind('telegram',user,b.id).run();await saveChat(db,user,'idle');return sendTelegram(env,user,matches.length?`Telegram підключено 🩷\nВаші записи:\n${matches.map(b=>`${b.day} о ${fmt(b.start_min)} — ${b.service_name}`).join('\n')}\n\nТепер сюди приходитимуть повідомлення про перенесення, скасування та нагадування.`:'Telegram підключено 🩷\nЗаписів на цей номер поки не знайдено. Наступні записи з цим номером автоматично підключаться до сповіщень.',{remove_keyboard:true})}
  if(s?.stage==='contact'&&message?.contact){if(String(message.contact.user_id||'')!==user)return sendTelegram(env,user,'Поділіться, будь ласка, власним контактом.',contactKeyboard());const phone=String(message.contact.phone_number||'').trim();if(!/^\+?[0-9 ()-]{9,30}$/.test(phone))return sendTelegram(env,user,'Не вдалося прочитати номер. Спробуйте ще раз.',contactKeyboard());const name=String(message.contact.first_name||message.from?.first_name||'Без імені').slice(0,80);await db.prepare('INSERT INTO telegram_profiles(user_id,name,phone,updated_at) VALUES (?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET name=excluded.name,phone=excluded.phone,updated_at=excluded.updated_at').bind(user,name,phone,new Date().toISOString()).run();await saveChat(db,user,'confirm',{name,phone});const service=await one(db,'SELECT name,price FROM services WHERE id=? AND active=1',s.service_id);return sendTelegram(env,user,`Перевірте запис:\n${service?.name||'Послуга'} · ${service?.price||0} ₴\n${s.day} о ${s.time}\n${name} · ${phone}`,keyboard([[btn('✅ Підтвердити','confirm')],[btn('Скасувати','stop')]]))}
  if(s?.stage==='contact'&&text==='Ввести вручну'){await saveChat(db,user,'name');return sendTelegram(env,user,'Як вас звати? Напишіть ім’я повідомленням.');}
  if(data==='change_contact'&&s?.stage==='confirm'){await saveChat(db,user,'contact');return sendTelegram(env,user,'Поділіться новим контактом або оберіть ручне введення.',contactKeyboard())}
  if(s?.stage==='name'&&text&&!text.startsWith('/')){try{const name=required(text,'Ім’я',80);await saveChat(db,user,'phone',{name});return sendTelegram(env,user,'Напишіть номер телефону, наприклад +380XXXXXXXXX.')}catch(e){if(e instanceof Problem)return sendTelegram(env,user,e.message);throw e}}
  if(s?.stage==='phone'&&(text||message?.contact)){const phone=message?.contact?.phone_number||text;if(!/^\+?[0-9 ()-]{9,30}$/.test(phone))return sendTelegram(env,user,'Перевірте номер телефону й надішліть ще раз.');await saveChat(db,user,'confirm',{phone});const service=await one(db,'SELECT name,price FROM services WHERE id=? AND active=1',s.service_id);return sendTelegram(env,user,`Перевірте запис:\n${service?.name||'Послуга'} · ${service?.price||0} ₴\n${s.day} о ${s.time}\n${s.name} · ${phone}`,keyboard([[btn('✅ Підтвердити','confirm')],[btn('Скасувати','stop')]]))}
  if(data==='confirm'&&s?.stage==='confirm'){await saveChat(db,user,'processing');try{await booking(db,env,{service_ids:chosenIds(s).length?chosenIds(s):[s.service_id],day:s.day,time:s.time,name:s.name,phone:s.phone},false,ctx,user);await saveChat(db,user,'idle',{category:null,service_id:null,service_ids:'[]',day:null,time:null,name:null,phone:null});return}catch(e){await saveChat(db,user,'confirm');if(e instanceof Problem)return sendTelegram(env,user,`${e.message}\nОберіть інший час або скасуйте запис.`,keyboard([[btn('← Інший час','retrytime')],[btn('Скасувати','stop')]]));throw e}}
  if(data==='retrytime'&&s?.stage==='confirm')return chatTimes(db,env,user);
  return sendTelegram(env,user,'Натисніть кнопку, щоб почати запис.',keyboard([[btn('📅 Записатися','book')],[btn('Мої записи','mine')],[btn('📍 Адреса','address'),btn('📷 Instagram','instagram')]]))
}
async function route(req,env,ctx){const db=env.DB;if(!db)throw new Problem('База даних не підключена',500);const url=new URL(req.url),p=url.pathname,m=req.method;
  if(m==='GET'&&p.startsWith('/gallery-files/')){if(!env.GALLERY)throw new Problem('Сховище фото не підключено',500);const key=decodeURIComponent(p.slice('/gallery-files/'.length));if(!key||key.includes('..'))throw new Problem('Фото не знайдено',404);const object=await env.GALLERY.get(key);if(!object)throw new Problem('Фото не знайдено',404);const headers=new Headers();object.writeHttpMetadata(headers);headers.set('etag',object.httpEtag);headers.set('cache-control','public, max-age=31536000, immutable');headers.set('x-content-type-options','nosniff');return new Response(object.body,{headers})}
  if(m==='GET'&&p.startsWith('/calendar/')){if(!env.CALENDAR_FEED_KEY||env.CALENDAR_FEED_KEY.length<32||!secretEq(p.slice('/calendar/'.length),env.CALENDAR_FEED_KEY+'.ics'))throw new Problem('Адресу не знайдено',404);const bookings=await all(db,"SELECT b.id,b.day,b.start_min,b.end_min,b.service_name,b.client_name,b.phone,b.contact_type,b.contact_value,b.created_at,b.status,c.note AS client_note FROM bookings b LEFT JOIN clients c ON c.id=b.client_id WHERE b.status IN ('confirmed','completed') AND b.day<=? ORDER BY b.day,b.start_min",plusDays(today(),365));return new Response(calendarFeed(bookings),{headers:{'content-type':'text/calendar; charset=utf-8','cache-control':'private, max-age=300','x-content-type-options':'nosniff'}})}
  if(m==='POST'&&p==='/webhooks/telegram'){if(!env.TELEGRAM_WEBHOOK_SECRET||!secretEq(req.headers.get('x-telegram-bot-api-secret-token'),env.TELEGRAM_WEBHOOK_SECRET))throw new Problem('Заборонено',403);const update=await body(req);try{await handleTelegram(update,env,ctx)}catch(e){console.error('Telegram webhook error',e)}return json(ok())}
  if(m==='GET'&&p==='/api/services')return json(await all(db,'SELECT * FROM services WHERE active=1 ORDER BY category,id'));
  if(m==='GET'&&p==='/api/categories')return json(await all(db,'SELECT id,name FROM categories WHERE active=1 ORDER BY name'));
  if(m==='GET'&&p==='/api/gallery'){const rows=await all(db,'SELECT id,url,caption FROM gallery WHERE active=1 ORDER BY sort_order,id');return json(rows.map(x=>{try{const u=new URL(x.url,req.url);if(u.pathname.startsWith('/gallery-files/'))return {...x,url:u.pathname}}catch{}return x}))}
  if(m==='GET'&&p==='/api/public-info')return json(Object.fromEntries((await all(db,"SELECT key,value FROM settings WHERE key IN ('address','contact','instagram')")).map(x=>[x.key,x.value])));
  if(m==='GET'&&p==='/api/telegram-link'){if(!env.TELEGRAM_BOT_TOKEN)throw new Problem('Telegram-бот не налаштований',404);const me=await telegramApi(env,'getMe',{});if(!me?.username)throw new Problem('У бота немає username',404);return json({url:`https://t.me/${me.username}?start=connect`})}
  if(m==='GET'&&p==='/api/days'){const from=today(),to=plusDays(from,90);return json(await configuredDays(db,from,to))}
  if(m==='GET'&&p==='/api/slots'){const d=day(url.searchParams.get('day'));let ids=url.searchParams.has('service_ids')?url.searchParams.get('service_ids').split(',').map(nint):[nint(url.searchParams.get('service_id'))];ids=[...new Set(ids)];if(!ids.length||ids.length>12||ids.some(x=>!Number.isInteger(x)||x<=0))throw new Problem('Оберіть послугу');const rows=await all(db,`SELECT minutes FROM services WHERE active=1 AND id IN (${ids.map(()=>'?').join(',')})`,...ids);if(rows.length!==ids.length)throw new Problem('Оберіть доступні послуги');return json(await available(db,d,rows.reduce((n,s)=>n+s.minutes,0)))}
  if(m==='POST'&&p==='/api/bookings')return json(await booking(db,env,await body(req),false,ctx),201);
  if(m==='GET'&&p==='/api/my-bookings'){const user=await tgIdentity(req.headers.get('x-telegram-init-data'),env);return json(await all(db,"SELECT id,day,start_min,end_min,service_name,price,status FROM bookings WHERE channel='telegram' AND channel_user_id=? AND status='confirmed' AND day>=? ORDER BY day,start_min",user,today()).then(rows=>rows.map(b=>({...b,start:fmt(b.start_min),end:fmt(b.end_min)}))))}
  let match=p.match(/^\/api\/my-bookings\/(\d+)\/(cancel|move)$/);if(m==='POST'&&match){const user=await tgIdentity(req.headers.get('x-telegram-init-data'),env),id=Number(match[1]),b=await one(db,"SELECT * FROM bookings WHERE id=? AND channel='telegram' AND channel_user_id=? AND status='confirmed'",id,user);if(!b)throw new Problem('Запис не знайдено',404);if(match[2]==='move')return json(await move(db,env,id,await body(req),ctx));const result=await db.prepare("UPDATE bookings SET status='cancelled' WHERE id=? AND status='confirmed'").bind(id).run();if(!result.meta.changes)throw new Problem('Запис не знайдено',404);queueMasterNotice(ctx,env,b,'cancelled');ctx.waitUntil(notify(env,b,'cancelled'));return json(ok())}
  if(!p.startsWith('/api/admin/'))return env.ASSETS.fetch(req);
  await admin(req,env);
  if(m==='GET'&&p==='/api/admin/services')return json(await all(db,'SELECT * FROM services ORDER BY category,id'));
  if(m==='GET'&&p==='/api/admin/categories')return json(await all(db,'SELECT * FROM categories ORDER BY name'));
  if(m==='POST'&&p==='/api/admin/categories'){const x=await body(req),name=required(x.name,'Категорія',80);const r=await db.prepare('INSERT INTO categories(name) VALUES (?) ON CONFLICT(name) DO UPDATE SET active=1').bind(name).run();return json({ok:true,id:r.meta.last_row_id})}
  if(m==='DELETE'&&p.match(/^\/api\/admin\/categories\/\d+$/)){const id=Number(p.split('/').pop());await db.prepare('UPDATE categories SET active=0 WHERE id=?').bind(id).run();return json(ok())}
  if(m==='GET'&&p==='/api/admin/gallery')return json(await all(db,'SELECT * FROM gallery ORDER BY sort_order,id'));
  if(m==='POST'&&p==='/api/admin/gallery'){if(!env.GALLERY)throw new Problem('Сховище фото не підключено',500);let form;try{form=await req.formData()}catch{throw new Problem('Не вдалося прочитати фото')};const file=form.get('photo'),caption=String(form.get('caption')||'').trim().slice(0,160);if(!(file instanceof File)||!file.size)throw new Problem('Оберіть фото');if(file.size>10*1024*1024)throw new Problem('Фото завелике. Максимум 10 МБ');const allowed=new Set(['image/jpeg','image/png','image/webp','image/heic','image/heif']);if(!allowed.has(file.type))throw new Problem('Підтримуються JPG, PNG, WEBP або HEIC');const ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/heic':'heic','image/heif':'heif'}[file.type],key=`${Date.now()}-${crypto.randomUUID()}.${ext}`;await env.GALLERY.put(key,file.stream(),{httpMetadata:{contentType:file.type}});const photoUrl=`/gallery-files/${encodeURIComponent(key)}`;try{const r=await db.prepare('INSERT INTO gallery(url,caption,sort_order) VALUES (?,?,?)').bind(photoUrl,caption,0).run();return json({id:r.meta.last_row_id,url:photoUrl})}catch(e){await env.GALLERY.delete(key);throw e}}
  if(m==='DELETE'&&p.match(/^\/api\/admin\/gallery\/\d+$/)){const id=Number(p.split('/').pop()),item=await one(db,'SELECT url FROM gallery WHERE id=?',id);if(item?.url){try{const u=new URL(item.url);if(u.pathname.startsWith('/gallery-files/')&&env.GALLERY)await env.GALLERY.delete(decodeURIComponent(u.pathname.slice('/gallery-files/'.length)))}catch{}}await db.prepare('DELETE FROM gallery WHERE id=?').bind(id).run();return json(ok())}
  if(m==='POST'&&p==='/api/admin/services'){const x=await body(req),category=required(x.category,'Категорія',80),name=required(x.name,'Назва',160),minutes=nint(x.minutes),price=nint(x.price),active=x.active?1:0;if(minutes<5||minutes>720||price<0||price>100000||!Number.isFinite(minutes)||!Number.isFinite(price))throw new Problem('Перевірте ціну та тривалість');await db.prepare('INSERT INTO categories(name) VALUES (?) ON CONFLICT(name) DO UPDATE SET active=1').bind(category).run();if(x.id){const result=await db.prepare('UPDATE services SET category=?,name=?,minutes=?,price=?,active=? WHERE id=?').bind(category,name,minutes,price,active,nint(x.id)).run();if(!result.meta.changes)throw new Problem('Послугу не знайдено',404);return json({id:nint(x.id)})}const r=await db.prepare('INSERT INTO services(category,name,minutes,price,active) VALUES (?,?,?,?,?)').bind(category,name,minutes,price,active).run();return json({id:r.meta.last_row_id})}
  if(m==='GET'&&p==='/api/admin/weekly-hours')return json(await weeklyTemplate(db));
  if(m==='PUT'&&p==='/api/admin/weekly-hours'){const x=await body(req);if(!Array.isArray(x.days)||x.days.length!==7)throw new Problem('Вкажіть сім днів тижня');const weekly={};for(let i=0;i<7;i++){const item=x.days[i];if(!item||typeof item.enabled!=='boolean')throw new Problem('Перевірте дні тижня');if(!item.enabled)continue;const start=minute(item.start),end=minute(item.end);if(start>=end)throw new Problem('Початок має бути раніше завершення');weekly[i]=[{start_min:start,end_min:end}]}await db.prepare("INSERT INTO settings(key,value) VALUES ('weekly_hours',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(JSON.stringify(weekly)).run();return json(weekly)}
  if(m==='GET'&&p==='/api/admin/month'){const month=url.searchParams.get('month');if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month||''))throw new Problem('Оберіть місяць');const from=`${month}-01`,to=plusDays(`${month}-01`,32).slice(0,7)+'-01';const [specific,bookingItems,closed,weekly]=await Promise.all([all(db,'SELECT day,COUNT(*) count FROM openings WHERE day>=? AND day<? GROUP BY day',from,to),all(db,"SELECT day,start_min,client_name,service_name FROM bookings WHERE day>=? AND day<? AND status IN ('confirmed','completed') ORDER BY day,start_min",from,to),all(db,"SELECT substr(key,9) day FROM settings WHERE key LIKE ? AND value='1'",`day_off:${month}-%`),weeklyTemplate(db)]);const off=new Set(closed.map(x=>x.day)),openings=[...specific],inherited_days=[],counts=new Map();for(const item of bookingItems)counts.set(item.day,(counts.get(item.day)||0)+1);const bookings=[...counts].map(([day,count])=>({day,count}));for(let d=from;d<to;d=plusDays(d,1))if(!off.has(d)&&!specific.some(x=>x.day===d)&&weekly[weekday(d)]?.length){openings.push({day:d,count:weekly[weekday(d)].length});inherited_days.push(d)}return json({openings,bookings,booking_items:bookingItems,days_off:[...off],inherited_days})}
  if(m==='GET'&&p==='/api/admin/day'){const d=day(url.searchParams.get('day'),false);const [busySetting,schedule,bookings]=await Promise.all([one(db,'SELECT value FROM settings WHERE key=?',`busy:${d}`),effectiveOpenings(db,d),all(db,"SELECT * FROM bookings WHERE day=? AND status IN ('confirmed','completed') ORDER BY start_min",d)]);return json({busy:JSON.parse(busySetting?.value||'[]').map(x=>({start:fmt(x.start),end:fmt(x.end)})),dayOff:schedule.source==='day_off',inherited:schedule.source==='weekly',openings:schedule.windows.map(x=>({start:fmt(x.start_min),end:fmt(x.end_min)})),bookings:bookings.map(x=>({...x,start:fmt(x.start_min),end:fmt(x.end_min),contact:x.contact_value||x.phone}))})}
  if(m==='PUT'&&p==='/api/admin/openings'){const x=await body(req),d=day(x.day),intervals=x.intervals;if(!Array.isArray(intervals)||intervals.length>8)throw new Problem('Передайте не більше восьми інтервалів');const ranges=intervals.map(v=>[minute(v.start),minute(v.end)]).sort((a,b)=>a[0]-b[0]);if(ranges.some(([a,b],i)=>a>=b||(i&&ranges[i-1][1]>a)))throw new Problem('Робочі інтервали не повинні перетинатися');const booked=await all(db,"SELECT start_min,end_min FROM bookings WHERE day=? AND status='confirmed'",d);if(booked.some(b=>!ranges.some(([a,z])=>a<=b.start_min&&b.end_min<=z)))throw new Problem('Спершу перенесіть або скасуйте записи поза новими годинами',409);const backupKey=`day_off_backup:${d}`,offKey=`day_off:${d}`;const oldRanges=ranges.length?[]:await all(db,'SELECT start_min,end_min FROM openings WHERE day=? ORDER BY start_min',d);const existingBackup=ranges.length?null:await one(db,'SELECT value FROM settings WHERE key=?',backupKey);const commands=[db.prepare('DELETE FROM openings WHERE day=?').bind(d),...ranges.map(([a,z])=>db.prepare('INSERT INTO openings(day,start_min,end_min) VALUES (?,?,?)').bind(d,a,z))];if(ranges.length)commands.push(db.prepare('DELETE FROM settings WHERE key IN (?,?)').bind(offKey,backupKey));else{if(!existingBackup&&oldRanges.length)commands.push(db.prepare('INSERT INTO settings(key,value) VALUES (?,?)').bind(backupKey,JSON.stringify(oldRanges)));commands.push(db.prepare("INSERT INTO settings(key,value) VALUES (?,'1') ON CONFLICT(key) DO UPDATE SET value='1'").bind(offKey))}await db.batch(commands);return json(ranges.map(([a,z])=>({start:fmt(a),end:fmt(z)})))}
  if(m==='POST'&&p==='/api/admin/undo-day-off'){const d=day((await body(req)).day),backupKey=`day_off_backup:${d}`,offKey=`day_off:${d}`;const saved=await one(db,'SELECT value FROM settings WHERE key=?',backupKey);let intervals=[];if(saved){try{intervals=JSON.parse(saved.value);if(!Array.isArray(intervals)||intervals.some(x=>!Number.isInteger(x.start_min)||!Number.isInteger(x.end_min)||x.start_min>=x.end_min))throw Error()}catch{throw new Problem('Не вдалося відновити попередні години',500)}}const commands=[db.prepare('DELETE FROM openings WHERE day=?').bind(d),...intervals.map(x=>db.prepare('INSERT INTO openings(day,start_min,end_min) VALUES (?,?,?)').bind(d,x.start_min,x.end_min)),db.prepare('DELETE FROM settings WHERE key IN (?,?)').bind(offKey,backupKey)];await db.batch(commands);return json({ok:true,restored:intervals.length>0})}
  if(m==='PUT'&&p==='/api/admin/busy'){const x=await body(req),d=day(x.day);if(!Array.isArray(x.intervals)||x.intervals.length>8)throw new Problem('Передайте не більше восьми проміжків');const ranges=x.intervals.map(v=>({start:minute(v.start),end:minute(v.end)})).sort((a,b)=>a.start-b.start);if(ranges.some((x,i)=>x.start>=x.end||(i&&ranges[i-1].end>x.start)))throw new Problem('Проміжки зайнятості не повинні перетинатися');const booked=await all(db,"SELECT start_min,end_min FROM bookings WHERE day=? AND status='confirmed'",d);if(ranges.some(x=>booked.some(b=>x.start<b.end_min&&x.end>b.start_min)))throw new Problem('На цей час уже є запис. Спочатку перенесіть або скасуйте його.',409);if(ranges.length)await db.prepare('INSERT INTO settings(key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind(`busy:${d}`,JSON.stringify(ranges)).run();else await db.prepare('DELETE FROM settings WHERE key=?').bind(`busy:${d}`).run();return json(ok())}
  if(m==='GET'&&p==='/api/admin/bookings'){const history=url.searchParams.get('view')==='history';return json(await all(db,history?"SELECT id,day,start_min,end_min,service_name,price,client_name,contact_type,contact_value,phone,status FROM bookings WHERE day<? OR status IN ('completed','cancelled','no_show') ORDER BY day DESC,start_min DESC LIMIT 300":"SELECT id,day,start_min,end_min,service_name,price,client_name,contact_type,contact_value,phone,status FROM bookings WHERE day>=? AND status='confirmed' ORDER BY day,start_min LIMIT 300",today()))}
  if(m==='POST'&&p==='/api/admin/bookings')return json(await booking(db,env,await body(req),true,ctx),201);
  if(m==='POST'&&p==='/api/admin/copy-week'){const start=day((await body(req)).day),target=plusDays(start,7);day(plusDays(target,6));const commands=[];for(let i=0;i<7;i++){const from=plusDays(start,i),to=plusDays(target,i);if(await one(db,'SELECT 1 FROM openings WHERE day=? LIMIT 1',to)||await one(db,'SELECT 1 FROM settings WHERE key=?',`day_off:${to}`))continue;const closed=await one(db,'SELECT 1 FROM settings WHERE key=?',`day_off:${from}`);if(closed){commands.push(db.prepare("INSERT INTO settings(key,value) VALUES (?,'1') ON CONFLICT(key) DO UPDATE SET value='1'").bind(`day_off:${to}`));continue}for(const x of await all(db,'SELECT start_min,end_min FROM openings WHERE day=?',from))commands.push(db.prepare('INSERT INTO openings(day,start_min,end_min) VALUES (?,?,?)').bind(to,x.start_min,x.end_min))}if(commands.length)await db.batch(commands);return json(ok())}
  if(m==='GET'&&p==='/api/admin/clients')return json(await all(db,"SELECT c.id,c.name,c.phone,c.contact_type,c.contact_value,c.note,SUM(CASE WHEN b.status='completed' THEN 1 ELSE 0 END) visits,COALESCE(SUM(CASE WHEN b.status='completed' THEN b.price ELSE 0 END),0) spent,MAX(CASE WHEN b.status='completed' THEN b.day END) last_visit FROM clients c LEFT JOIN bookings b ON b.client_id=c.id GROUP BY c.id ORDER BY c.name"));
  match=p.match(/^\/api\/admin\/clients\/(\d+)(\/note)?$/);if(match){const id=Number(match[1]);if(m==='GET'&&!match[2])return json(await all(db,'SELECT * FROM bookings WHERE client_id=? ORDER BY day DESC',id));if(m==='POST'&&match[2]){const note=(await body(req)).note;if(typeof note!=='string'||note.length>1000)throw new Problem('Нотатка занадто довга');await db.prepare('UPDATE clients SET note=? WHERE id=?').bind(note,id).run();return json(ok())}}
  if(m==='GET'&&p==='/api/admin/stats'){const sources=await all(db,"SELECT source,COUNT(*) count FROM bookings WHERE status NOT IN ('cancelled','no_show') GROUP BY source"),summary=await one(db,"SELECT COUNT(*) bookings,COALESCE(SUM(CASE WHEN status='completed' THEN price ELSE 0 END),0) revenue,COUNT(DISTINCT client_id) clients FROM bookings WHERE status NOT IN ('cancelled','no_show')"),upcoming=await one(db,"SELECT COUNT(*) count FROM bookings WHERE status='confirmed' AND day>=?",today());return json({sources,summary,upcoming:upcoming.count})}
  if(m==='GET'&&p==='/api/admin/settings')return json(await settings(db));
  if(m==='GET'&&p==='/api/admin/calendar-link'){if(!env.CALENDAR_FEED_KEY||env.CALENDAR_FEED_KEY.length<32)throw new Problem('Посилання календаря ще не налаштовано');return json({url:new URL(`/calendar/${env.CALENDAR_FEED_KEY}.ics`,req.url).href})}
  if(m==='POST'&&p==='/api/admin/connect-telegram'){if(!env.TELEGRAM_BOT_TOKEN||!env.TELEGRAM_WEBHOOK_SECRET)throw new Problem('Спочатку додайте ключі Telegram');try{await telegramApi(env,'setWebhook',{url:new URL('/webhooks/telegram',req.url).href,secret_token:env.TELEGRAM_WEBHOOK_SECRET,allowed_updates:['message','callback_query']})}catch(e){console.error(e);throw new Problem('Telegram не вдалося підключити. Перевірте токен бота і webhook secret (лише літери, цифри, _ або -).',502)}return json(ok())}
  if(m==='PUT'&&p==='/api/admin/settings'){const buffer=nint((await body(req)).buffer_minutes);if(![10,15,30].includes(buffer))throw new Problem('Перерва: 10, 15 або 30 хвилин');await db.prepare("UPDATE settings SET value=? WHERE key='buffer_minutes'").bind(String(buffer)).run();return json(ok())}
  if(m==='PUT'&&p==='/api/admin/profile'){const x=await body(req);for(const field of ['address','contact','instagram']){if(typeof x[field]!=='string'||x[field].length>200)throw new Problem('Надто довге поле профілю')}await db.batch(['address','contact','instagram'].map(field=>db.prepare('INSERT INTO settings(key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind(field,x[field].trim())));return json(ok())}
  match=p.match(/^\/api\/admin\/bookings\/(\d+)\/(move|complete|cancel|no-show|edit)$/);if(m==='POST'&&match){const id=Number(match[1]);if(match[2]==='edit')return editBooking(db,env,id,await body(req),ctx);if(match[2]==='move')return json(await move(db,env,id,await body(req),ctx));const b=await one(db,"SELECT * FROM bookings WHERE id=? AND status='confirmed'",id);if(!b)throw new Problem('Запис не знайдено',404);if(match[2]==='no-show'&&(b.day>today()||b.day===today()&&b.start_min>nowMinute()))throw new Problem('Позначити неявку можна після початку запису',409);const result=await db.prepare('UPDATE bookings SET status=? WHERE id=? AND status=\'confirmed\'').bind(match[2]==='complete'?'completed':match[2]==='no-show'?'no_show':'cancelled',id).run();if(!result.meta.changes)throw new Problem('Запис уже змінено',409);if(match[2]==='cancel'){queueMasterNotice(ctx,env,b,'cancelledByMaster');ctx.waitUntil(notify(env,b,'cancelled'))}return json(ok())}
  throw new Problem('Адресу не знайдено',404)
}
async function scheduled(env){const db=env.DB;if(!env.TELEGRAM_BOT_TOKEN)return;const next=await all(db,"SELECT * FROM bookings WHERE status='confirmed' AND channel='telegram' AND day>=? AND day<=?",today(),plusDays(today(),2));for(const b of next){
 const local=new Date(`${b.day}T00:00:00Z`);const dayPart=new Intl.DateTimeFormat('en-US',{timeZone:TZ,timeZoneName:'shortOffset'}).formatToParts(local).find(x=>x.type==='timeZoneName')?.value||'GMT+3';const offset=Number(dayPart.match(/GMT([+-]\d+)/)?.[1]||3);const remaining=(Date.parse(`${b.day}T${fmt(b.start_min)}:00Z`)-offset*3600000-Date.now())/60000;
 for(const [kind,minutes] of [['24h',1440],['2h',120]])if(remaining>minutes-15&&remaining<=minutes){const insert=await db.prepare('INSERT OR IGNORE INTO notifications(booking_id,kind,sent_at) VALUES (?,?,?)').bind(b.id,kind,new Date().toISOString()).run();if(insert.meta.changes)try{await sendTelegram(env,b.channel_user_id,`Нагадуємо про запис 🩷\n${b.day} о ${fmt(b.start_min)}\n${b.service_name}`)}catch{await db.prepare('DELETE FROM notifications WHERE booking_id=? AND kind=?').bind(b.id,kind).run()}}}
 if(env.TELEGRAM_ADMIN_CHAT_ID&&nowMinute()<9*60&&nowMinute()>=8*60+45){const insert=await db.prepare('INSERT OR IGNORE INTO daily_digests(day,sent_at) VALUES (?,?)').bind(today(),new Date().toISOString()).run();if(insert.meta.changes){const visits=await all(db,"SELECT * FROM bookings WHERE day=? AND status='confirmed' ORDER BY start_min",today());try{await sendTelegram(env,env.TELEGRAM_ADMIN_CHAT_ID,`Записи на сьогодні — ${visits.length}\n`+visits.map(x=>`${fmt(x.start_min)} — ${x.client_name}, ${x.service_name}`).join('\n'))}catch{await db.prepare('DELETE FROM daily_digests WHERE day=?').bind(today()).run()}}}}
export default {async fetch(req,env,ctx){try{return await route(req,env,ctx)}catch(e){if(e instanceof Problem)return json({error:e.message},e.status);console.error(e);return json({error:'Внутрішня помилка сервера'},500)}},async scheduled(event,env,ctx){ctx.waitUntil(scheduled(env))}};
