const TZ = 'Europe/Kyiv';
const encoder = new TextEncoder();
class Problem extends Error { constructor(message, status=400) { super(message); this.status=status; } }
const json = (value, status=200) => new Response(JSON.stringify(value), {status, headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}});
const ok = () => ({ok:true});
const one = (db, sql, ...args) => db.prepare(sql).bind(...args).first();
const all = async (db, sql, ...args) => (await db.prepare(sql).bind(...args).all()).results;
const pad = n => String(n).padStart(2,'0');
const fmt = n => `${pad(Math.floor(n/60))}:${pad(n%60)}`;
const today = () => new Intl.DateTimeFormat('sv-SE',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const nowMinute = () => {const parts=new Intl.DateTimeFormat('en-GB',{timeZone:TZ,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date());return Number(parts.find(x=>x.type==='hour').value)*60+Number(parts.find(x=>x.type==='minute').value)};
const plusDays = (day,n) => new Date(Date.parse(day+'T12:00:00Z')+n*86400000).toISOString().slice(0,10);
function day(value, future=true){if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value)||Number.isNaN(Date.parse(value+'T12:00:00Z'))||new Date(value+'T12:00:00Z').toISOString().slice(0,10)!==value)throw new Problem('Невірна дата');if(future&&(value<today()||value>plusDays(today(),90)))throw new Problem('Оберіть дату в межах наступних 90 днів');return value}
function minute(v){if(typeof v!=='string'||!/^([01]\d|2[0-3]):[0-5]\d$/.test(v))throw new Problem('Вкажіть час у форматі ГГ:ХХ');return Number(v.slice(0,2))*60+Number(v.slice(3))}
function required(v,label,max){if(typeof v!=='string'||!v.trim()||v.trim().length>max)throw new Problem(`Перевірте поле «${label}»`);return v.trim()}
const nint = v => Number.isInteger(Number(v)) ? Number(v) : NaN;
const secretEq = (a,b) => {if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0};
const hmac = async (key,data) => new Uint8Array(await crypto.subtle.sign('HMAC',await crypto.subtle.importKey('raw',key,{name:'HMAC',hash:'SHA-256'},false,['sign']),encoder.encode(data)));
const hex = bytes => Array.from(bytes).map(x=>x.toString(16).padStart(2,'0')).join('');
const icsText = v => String(v).replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');
function calendarFeed(bookings){const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Online Zapys//Booking Calendar//UK','CALSCALE:GREGORIAN','X-WR-CALNAME:Мої записи','X-WR-TIMEZONE:Europe/Kyiv'];for(const b of bookings){const stamp=b.day.replaceAll('-',''),at=n=>`${stamp}T${pad(Math.floor(n/60))}${pad(n%60)}00`;lines.push('BEGIN:VEVENT',`UID:booking-${b.id}@online-zapys`,`DTSTAMP:${new Date(b.created_at).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}`,`DTSTART;TZID=Europe/Kyiv:${at(b.start_min)}`,`DTEND;TZID=Europe/Kyiv:${at(b.end_min)}`,`SUMMARY:${icsText(b.service_name)}`,'END:VEVENT')}lines.push('END:VCALENDAR');return lines.join('\r\n')+'\r\n'}
async function tgIdentity(raw,env){if(!env.TELEGRAM_BOT_TOKEN||!raw||raw.length>4096)throw new Problem('Немає даних Telegram',401);const p=new URLSearchParams(raw),signature=p.get('hash');p.delete('hash');const check=[...p.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join('\n');const key=await hmac(encoder.encode('WebAppData'),env.TELEGRAM_BOT_TOKEN);if(!secretEq(signature,hex(await hmac(key,check))))throw new Problem('Неправильний підпис Telegram',401);let u;try{u=JSON.parse(p.get('user'));if(!Number.isInteger(Number(u.id))||Math.abs(Date.now()/1000-Number(p.get('auth_date')))>86400)throw Error()}catch{throw new Problem('Сесія Telegram застаріла',401)}return String(u.id)}
async function admin(req,env){if(env.BOOKING_ADMIN_KEY?.length<16)throw new Problem('Адмінключ не налаштований',500);if(secretEq(req.headers.get('x-admin-key'),env.BOOKING_ADMIN_KEY))return;try{if(env.ADMIN_TELEGRAM_ID&&await tgIdentity(req.headers.get('x-telegram-init-data'),env)===env.ADMIN_TELEGRAM_ID)return}catch{}throw new Problem('Потрібен доступ майстра',403)}
async function body(req){let str=await req.text();if(str.length>16384)throw new Problem('Завеликий запит');try{const v=JSON.parse(str);if(v&&typeof v==='object'&&!Array.isArray(v))return v}catch{}throw new Problem('Некоректні дані запиту')}
async function settings(db){return Object.fromEntries((await all(db,'SELECT key,value FROM settings')).map(x=>[x.key,x.value]))}
async function available(db,d,duration,exclude=-1){const [windows,bookings,setting]=await Promise.all([all(db,'SELECT start_min,end_min FROM openings WHERE day=? ORDER BY start_min',d),all(db,"SELECT id,start_min,end_min FROM bookings WHERE day=? AND status='confirmed' AND id!=?",d,exclude),one(db,"SELECT value FROM settings WHERE key='buffer_minutes'")]);const buffer=Number(setting?.value||10),out=new Set();for(const w of windows){for(let pos=Math.ceil(w.start_min/5)*5;pos+duration<=w.end_min;pos+=5){if(d===today()&&pos<=nowMinute())continue;if(bookings.every(b=>pos>=b.end_min+buffer||pos+duration+buffer<=b.start_min))out.add(fmt(pos))}}return [...out].sort()}
async function telegramApi(env,method,payload){if(!env.TELEGRAM_BOT_TOKEN)throw Error('Telegram token missing');const response=await fetch(`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const result=await response.json();if(!result.ok)throw Error(`Telegram ${method}: ${result.description||response.status}`);return result.result}
async function sendTelegram(env,recipient,text,markup){return telegramApi(env,'sendMessage',{chat_id:recipient,text,...(markup?{reply_markup:markup}:{})})}
async function notify(env,b,kind){if(b?.channel==='telegram'&&b.channel_user_id)await sendTelegram(env,b.channel_user_id,`${{created:'Ваш запис підтверджено',moved:'Ваш запис перенесено',cancelled:'Ваш запис скасовано'}[kind]} 🩷\n${b.day} о ${fmt(b.start_min)}\n${b.service_name}`,{remove_keyboard:true})}
async function booking(db,env,data,manual,ctx,trustedTelegramUser=null){const d=day(data.day),start=minute(data.time);let ids=Array.isArray(data.service_ids)?data.service_ids.map(nint).filter(Number.isInteger):[nint(data.service_id)];ids=[...new Set(ids)];if(!ids.length||ids.length>12)throw new Problem('Оберіть послугу');let name=String(data.name||'').trim(),phone=String(data.phone||'').trim();if(name.length>80||phone.length>60)throw new Problem('Перевірте контактні дані');const contactType=String(data.contact_type||'Телефон').trim()||'Телефон';const contactValue=String(data.contact_value||phone).trim();if(!manual&&!contactValue)throw new Problem('Вкажіть контакт клієнта');if(!['Телефон','Instagram','Telegram','Без контакту'].includes(contactType)||!manual&&contactType==='Без контакту')throw new Problem('Оберіть тип контакту');if(contactValue&&contactType==='Телефон'&&!/^\+?[0-9 ()-]{9,30}$/.test(contactValue))throw new Problem('Перевірте номер телефону');if(!name)name='Без імені';if(!phone)phone=contactType==='Телефон'?contactValue:'';const marks=ids.map(()=>'?').join(',');const services=await all(db,`SELECT * FROM services WHERE active=1 AND id IN (${marks})`,...ids);if(services.length!==ids.length)throw new Problem('Одна з послуг вже недоступна',409);const service=services[0],duration=services.reduce((sum,s)=>sum+s.minutes,0),totalPrice=services.reduce((sum,s)=>sum+s.price,0),serviceName=services.map(s=>s.name).join(' + ');let channel=null,user=null;if(!manual&&trustedTelegramUser){user=String(trustedTelegramUser);channel='telegram'}else if(!manual&&data.telegram_init_data){user=await tgIdentity(data.telegram_init_data,env);channel='telegram'}let source=manual?'manual':channel||data.source;if(!['web','telegram','instagram','viber','manual'].includes(source))source='web';
  if(start%5||d===today()&&start<=nowMinute())throw new Problem('Оберіть доступний час',409);
  // The availability and overlap checks belong to one atomic INSERT statement.
  const clientKey=contactValue?`${contactType}:${contactValue}`:`anon-${crypto.randomUUID()}`;await db.prepare('INSERT INTO clients(phone,name,contact_type,contact_value) VALUES (?,?,?,?) ON CONFLICT(phone) DO UPDATE SET name=excluded.name,contact_type=excluded.contact_type,contact_value=excluded.contact_value').bind(clientKey,name,contactType,contactValue).run();
  const client=await one(db,'SELECT id FROM clients WHERE phone=?',clientKey);const buffer=Number((await one(db,"SELECT value FROM settings WHERE key='buffer_minutes'"))?.value||10);
  const result=await db.prepare(`INSERT INTO bookings(day,start_min,end_min,service_id,service_name,price,client_name,phone,source,created_at,client_id,channel,channel_user_id,contact_type,contact_value)
  SELECT ?,?,?,?,?,?,?,?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM openings WHERE day=? AND start_min<=? AND end_min>=?)
  AND NOT EXISTS(SELECT 1 FROM bookings WHERE day=? AND status='confirmed' AND NOT (? >= end_min+? OR ?+?+? <= start_min))`).bind(d,start,start+duration,service.id,serviceName,totalPrice,name,phone,source,new Date().toISOString(),client.id,channel,user,contactType,contactValue,d,start,start+duration,d,start,buffer,start,duration,buffer).run();
  if(!result.meta.changes)throw new Problem('Цей час уже зайнятий або недоступний. Оберіть інший.',409);
  const b=await one(db,'SELECT * FROM bookings WHERE id=?',result.meta.last_row_id);if(channel)ctx.waitUntil(notify(env,b,'created'));return {id:b.id,day:d,start:fmt(start),end:fmt(b.end_min),service:b.service_name,price:b.price}}
async function move(db,env,id,data,ctx){const d=day(data.day),start=minute(data.time);if(start%5||d===today()&&start<=nowMinute())throw new Problem('Оберіть доступний час',409);const b=await one(db,"SELECT * FROM bookings WHERE id=? AND status='confirmed'",id);if(!b)throw new Problem('Запис не знайдено',404);const duration=b.end_min-b.start_min,buffer=Number((await one(db,"SELECT value FROM settings WHERE key='buffer_minutes'"))?.value||10);const result=await db.prepare(`UPDATE bookings SET day=?,start_min=?,end_min=? WHERE id=? AND status='confirmed'
 AND EXISTS(SELECT 1 FROM openings WHERE day=? AND start_min<=? AND end_min>=?)
 AND NOT EXISTS(SELECT 1 FROM bookings other WHERE other.day=? AND other.status='confirmed' AND other.id!=? AND NOT (? >= other.end_min+? OR ?+?+?<=other.start_min))`).bind(d,start,start+duration,id,d,start,start+duration,d,id,start,buffer,start,duration,buffer).run();if(!result.meta.changes)throw new Problem('Новий час зайнятий або недоступний',409);await db.prepare('DELETE FROM notifications WHERE booking_id=?').bind(id).run();ctx.waitUntil(notify(env,{...b,day:d,start_min:start},'moved'));return {ok:true,day:d,start:fmt(start)}}
const keyboard = rows => ({inline_keyboard:rows});
const btn = (text,data) => ({text,callback_data:data});
const contactKeyboard = () => ({keyboard:[[{text:'Поділитися контактом',request_contact:true}],[{text:'Ввести вручну'}]],resize_keyboard:true,one_time_keyboard:true});
async function chatSession(db,user){return one(db,'SELECT * FROM telegram_chat_sessions WHERE user_id=?',user)}
async function saveChat(db,user,stage,values={}){const s={...(await chatSession(db,user)),...values};await db.prepare(`INSERT INTO telegram_chat_sessions(user_id,stage,category,service_id,day,time,name,phone,service_ids,updated_at)
 VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET stage=excluded.stage,category=excluded.category,service_id=excluded.service_id,day=excluded.day,time=excluded.time,name=excluded.name,phone=excluded.phone,service_ids=excluded.service_ids,updated_at=excluded.updated_at`).bind(user,stage,s.category??null,s.service_id??null,s.day??null,s.time??null,s.name??null,s.phone??null,s.service_ids??'[]',new Date().toISOString()).run()}
function chosenIds(session){try{const ids=JSON.parse(session?.service_ids||'[]');return Array.isArray(ids)?ids.filter(Number.isInteger).slice(0,12):[]}catch{return []}}
async function chosenServices(db,session){const ids=chosenIds(session);if(!ids.length&&session?.service_id)ids.push(session.service_id);if(!ids.length)return [];const rows=await all(db,`SELECT * FROM services WHERE active=1 AND id IN (${ids.map(()=>'?').join(',')})`,...ids);return rows.length===ids.length?rows:[]}
async function chatServices(db,env,user,reset=true){const categories=await all(db,'SELECT DISTINCT category FROM services WHERE active=1 ORDER BY category');if(!categories.length)return sendTelegram(env,user,'Зараз немає доступних послуг. Спробуйте пізніше.');await saveChat(db,user,'category',reset?{category:null,service_id:null,service_ids:'[]',day:null,time:null,name:null,phone:null}:{category:null,day:null,time:null});const count=chosenIds(await chatSession(db,user)).length,rows=categories.map((x,i)=>[btn(x.category,`cat:${i}`)]);if(count)rows.push([btn(`✅ Готово · ${count} послуг`,`done_services`)]);rows.push([btn('Скасувати','stop')]);return sendTelegram(env,user,'Оберіть категорію послуг:',keyboard(rows))}
async function chatCategory(db,env,user,category){const s=await chatSession(db,user),services=await all(db,'SELECT id,name,minutes,price FROM services WHERE category=? AND active=1 ORDER BY id',category),chosen=chosenIds(s);await saveChat(db,user,'service',{category});const rows=services.map(x=>[btn(`${chosen.includes(x.id)?'✓ ':''}${x.name.slice(0,37)} · ${x.price} ₴`,`svc:${x.id}`)]);if(chosen.length)rows.push([btn(`✅ Готово · ${chosen.length} послуг`,'done_services')]);rows.push([btn('← Категорії','categories')]);return sendTelegram(env,user,`Категорія: ${category}\nМожна вибрати кілька послуг:`,keyboard(rows))}
async function chatDays(db,env,user,offset=0){const s=await chatSession(db,user),services=await chosenServices(db,s);if(!services.length)return chatServices(db,env,user);const duration=services.reduce((n,x)=>n+x.minutes,0),price=services.reduce((n,x)=>n+x.price,0);const dates=await all(db,'SELECT DISTINCT day FROM openings WHERE day>=? AND day<=? ORDER BY day',today(),plusDays(today(),90));const page=dates.slice(offset,offset+7),rows=[];for(const x of page){if((await available(db,x.day,duration)).length)rows.push([btn(x.day,`day:${x.day}`)])}if(offset+7<dates.length)rows.push([btn('Наступні дні →',`days:${offset+7}`)]);if(offset)rows.push([btn('← Попередні дні',`days:${Math.max(0,offset-7)}`)]);rows.push([btn('← Послуги','categories')]);await saveChat(db,user,'day',{day:null,time:null});return sendTelegram(env,user,`${services.map(x=>x.name).join(' + ')} · ${duration} хв · ${price} ₴\nОберіть дату${page.length&&!rows.some(r=>r[0].callback_data.startsWith('day:'))?' (на цій сторінці вільних годин немає)':''}:`,keyboard(rows))}
async function chatTimes(db,env,user,offset=0){const s=await chatSession(db,user),services=await chosenServices(db,s);if(!services.length||!s?.day)return chatServices(db,env,user);const slots=await available(db,day(s.day),services.reduce((n,x)=>n+x.minutes,0)),rows=[];for(let i=offset;i<Math.min(offset+8,slots.length);i+=2)rows.push(slots.slice(i,i+2).map(t=>btn(t,`time:${t}`)));const nav=[];if(offset)nav.push(btn('←',`times:${Math.max(0,offset-8)}`));if(offset+8<slots.length)nav.push(btn('→',`times:${offset+8}`));if(nav.length)rows.push(nav);rows.push([btn('← Дати','days:0')]);await saveChat(db,user,'time',{time:null});return sendTelegram(env,user,`Дата: ${s.day}. ${slots.length?'Оберіть вільний час:':'Вільного часу немає, оберіть іншу дату.'}`,keyboard(rows))}
async function handleTelegram(update,env,ctx){const db=env.DB,callback=update.callback_query,message=update.message,chat=callback?.message?.chat||message?.chat;if(chat?.type!=='private')return;const user=String(callback?.from?.id??message?.from?.id??'');if(!user||user!==String(chat.id))return;if(callback)await telegramApi(env,'answerCallbackQuery',{callback_query_id:callback.id});const data=callback?.data||'',text=message?.text?.trim(),s=await chatSession(db,user);
  if(text?.startsWith('/start')||text==='/cancel'||data==='stop'){await saveChat(db,user,'idle',{category:null,service_id:null,service_ids:'[]',day:null,time:null,name:null,phone:null});return sendTelegram(env,user,'Вітаємо! Тут можна записатися прямо в чаті 🩷',keyboard([[btn('📅 Записатися','book')],[btn('Мої записи','mine')]]))}
  if(text==='/book'||data==='book')return chatServices(db,env,user);
  if(data==='categories'&&['service','day'].includes(s?.stage))return chatServices(db,env,user,false);
  if(text==='/mybookings'||data==='mine'){const rows=await all(db,"SELECT day,start_min,service_name FROM bookings WHERE channel='telegram' AND channel_user_id=? AND status='confirmed' AND day>=? ORDER BY day,start_min LIMIT 10",user,today());return sendTelegram(env,user,rows.length?'Ваші найближчі записи:\n'+rows.map(x=>`${x.day} о ${fmt(x.start_min)} — ${x.service_name}`).join('\n'):'Майбутніх записів немає.',keyboard([[btn('📅 Новий запис','book')]]))}
  if(data.startsWith('cat:')&&s?.stage==='category'){const categories=await all(db,'SELECT DISTINCT category FROM services WHERE active=1 ORDER BY category'),category=categories[nint(data.slice(4))]?.category;if(!category)return chatServices(db,env,user,false);return chatCategory(db,env,user,category)}
  if(data.startsWith('svc:')&&s?.stage==='service'){const service=await one(db,'SELECT id FROM services WHERE id=? AND category=? AND active=1',nint(data.slice(4)),s.category);if(!service)return chatServices(db,env,user,false);const ids=chosenIds(s),index=ids.indexOf(service.id);if(index>=0)ids.splice(index,1);else if(ids.length<12)ids.push(service.id);await saveChat(db,user,'service',{service_ids:JSON.stringify(ids),service_id:ids[0]??null});return chatCategory(db,env,user,s.category)}
  if(data==='done_services'&&['category','service'].includes(s?.stage)){if(!(await chosenServices(db,s)).length)return chatServices(db,env,user,false);await saveChat(db,user,'day');return chatDays(db,env,user)}
  if(data.startsWith('days:')&&['day','time'].includes(s?.stage)){const offset=nint(data.slice(5));if(offset>=0&&offset<=90)return chatDays(db,env,user,offset)}
  if(data.startsWith('day:')&&s?.stage==='day'){const d=day(data.slice(4)),services=await chosenServices(db,s);if(services.length&&(await available(db,d,services.reduce((n,x)=>n+x.minutes,0))).length){await saveChat(db,user,'time',{day:d});return chatTimes(db,env,user)}return chatDays(db,env,user)}
  if(data.startsWith('times:')&&s?.stage==='time'){const offset=nint(data.slice(6));if(offset>=0&&offset<200)return chatTimes(db,env,user,offset)}
  if(data.startsWith('time:')&&s?.stage==='time'){const time=data.slice(5),services=await chosenServices(db,s),duration=services.reduce((n,x)=>n+x.minutes,0);if(services.length&&(await available(db,s.day,duration)).includes(time)){const profile=await one(db,'SELECT name,phone FROM telegram_profiles WHERE user_id=?',user);if(profile?.name&&profile?.phone){await saveChat(db,user,'confirm',{time,name:profile.name,phone:profile.phone});return sendTelegram(env,user,`Перевірте запис:\n${services.map(x=>x.name).join(' + ')} · ${services.reduce((n,x)=>n+x.price,0)} ₴\n${s.day} о ${time}\n${profile.name} · ${profile.phone}`,keyboard([[btn('✅ Підтвердити','confirm')],[btn('Змінити контакт','change_contact')],[btn('Скасувати','stop')]]))}await saveChat(db,user,'contact',{time});return sendTelegram(env,user,'Хочете поділитися контактом, щоб не вводити ім’я та номер щоразу?',contactKeyboard())}return chatTimes(db,env,user)}
  if(s?.stage==='contact'&&message?.contact){if(String(message.contact.user_id||'')!==user)return sendTelegram(env,user,'Поділіться, будь ласка, власним контактом.',contactKeyboard());const phone=String(message.contact.phone_number||'').trim();if(!/^\+?[0-9 ()-]{9,30}$/.test(phone))return sendTelegram(env,user,'Не вдалося прочитати номер. Спробуйте ще раз.',contactKeyboard());const name=String(message.contact.first_name||message.from?.first_name||'Без імені').slice(0,80);await db.prepare('INSERT INTO telegram_profiles(user_id,name,phone,updated_at) VALUES (?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET name=excluded.name,phone=excluded.phone,updated_at=excluded.updated_at').bind(user,name,phone,new Date().toISOString()).run();await saveChat(db,user,'confirm',{name,phone});const service=await one(db,'SELECT name,price FROM services WHERE id=? AND active=1',s.service_id);return sendTelegram(env,user,`Перевірте запис:\n${service?.name||'Послуга'} · ${service?.price||0} ₴\n${s.day} о ${s.time}\n${name} · ${phone}`,keyboard([[btn('✅ Підтвердити','confirm')],[btn('Скасувати','stop')]]))}
  if(s?.stage==='contact'&&text==='Ввести вручну'){await saveChat(db,user,'name');return sendTelegram(env,user,'Як вас звати? Напишіть ім’я повідомленням.');}
  if(data==='change_contact'&&s?.stage==='confirm'){await saveChat(db,user,'contact');return sendTelegram(env,user,'Поділіться новим контактом або оберіть ручне введення.',contactKeyboard())}
  if(s?.stage==='name'&&text&&!text.startsWith('/')){try{const name=required(text,'Ім’я',80);await saveChat(db,user,'phone',{name});return sendTelegram(env,user,'Напишіть номер телефону, наприклад +380XXXXXXXXX.')}catch(e){if(e instanceof Problem)return sendTelegram(env,user,e.message);throw e}}
  if(s?.stage==='phone'&&(text||message?.contact)){const phone=message?.contact?.phone_number||text;if(!/^\+?[0-9 ()-]{9,30}$/.test(phone))return sendTelegram(env,user,'Перевірте номер телефону й надішліть ще раз.');await saveChat(db,user,'confirm',{phone});const service=await one(db,'SELECT name,price FROM services WHERE id=? AND active=1',s.service_id);return sendTelegram(env,user,`Перевірте запис:\n${service?.name||'Послуга'} · ${service?.price||0} ₴\n${s.day} о ${s.time}\n${s.name} · ${phone}`,keyboard([[btn('✅ Підтвердити','confirm')],[btn('Скасувати','stop')]]))}
  if(data==='confirm'&&s?.stage==='confirm'){await saveChat(db,user,'processing');try{await booking(db,env,{service_ids:chosenIds(s).length?chosenIds(s):[s.service_id],day:s.day,time:s.time,name:s.name,phone:s.phone},false,ctx,user);await saveChat(db,user,'idle',{category:null,service_id:null,service_ids:'[]',day:null,time:null,name:null,phone:null});return}catch(e){await saveChat(db,user,'confirm');if(e instanceof Problem)return sendTelegram(env,user,`${e.message}\nОберіть інший час або скасуйте запис.`,keyboard([[btn('← Інший час','retrytime')],[btn('Скасувати','stop')]]));throw e}}
  if(data==='retrytime'&&s?.stage==='confirm')return chatTimes(db,env,user);
  return sendTelegram(env,user,'Натисніть кнопку, щоб почати запис.',keyboard([[btn('📅 Записатися','book')],[btn('Мої записи','mine')]]))
}
async function route(req,env,ctx){const db=env.DB;if(!db)throw new Problem('База даних не підключена',500);const url=new URL(req.url),p=url.pathname,m=req.method;
  if(m==='GET'&&p.startsWith('/calendar/')){if(!env.CALENDAR_FEED_KEY||env.CALENDAR_FEED_KEY.length<32||!secretEq(p.slice('/calendar/'.length),env.CALENDAR_FEED_KEY+'.ics'))throw new Problem('Адресу не знайдено',404);const bookings=await all(db,"SELECT id,day,start_min,end_min,service_name,created_at FROM bookings WHERE status='confirmed' AND day>=? AND day<=? ORDER BY day,start_min",plusDays(today(),-30),plusDays(today(),365));return new Response(calendarFeed(bookings),{headers:{'content-type':'text/calendar; charset=utf-8','cache-control':'private, max-age=300','x-content-type-options':'nosniff'}})}
  if(m==='POST'&&p==='/webhooks/telegram'){if(!env.TELEGRAM_WEBHOOK_SECRET||!secretEq(req.headers.get('x-telegram-bot-api-secret-token'),env.TELEGRAM_WEBHOOK_SECRET))throw new Problem('Заборонено',403);const update=await body(req);try{await handleTelegram(update,env,ctx)}catch(e){console.error('Telegram webhook error',e)}return json(ok())}
  if(m==='GET'&&p==='/api/services')return json(await all(db,'SELECT * FROM services WHERE active=1 ORDER BY category,id'));
  if(m==='GET'&&p==='/api/categories')return json(await all(db,'SELECT id,name FROM categories WHERE active=1 ORDER BY name'));
  if(m==='GET'&&p==='/api/gallery')return json(await all(db,'SELECT id,url,caption FROM gallery WHERE active=1 ORDER BY sort_order,id'));
  if(m==='GET'&&p==='/api/public-info')return json(await settings(db));
  if(m==='GET'&&p==='/api/days'){const from=today(),to=plusDays(from,90);return json((await all(db,'SELECT DISTINCT day FROM openings WHERE day>=? AND day<=? ORDER BY day',from,to)).map(x=>x.day))}
  if(m==='GET'&&p==='/api/slots'){const d=day(url.searchParams.get('day'));let ids=url.searchParams.has('service_ids')?url.searchParams.get('service_ids').split(',').map(nint):[nint(url.searchParams.get('service_id'))];ids=[...new Set(ids)];if(!ids.length||ids.length>12||ids.some(x=>!Number.isInteger(x)||x<=0))throw new Problem('Оберіть послугу');const rows=await all(db,`SELECT minutes FROM services WHERE active=1 AND id IN (${ids.map(()=>'?').join(',')})`,...ids);if(rows.length!==ids.length)throw new Problem('Оберіть доступні послуги');return json(await available(db,d,rows.reduce((n,s)=>n+s.minutes,0)))}
  if(m==='POST'&&p==='/api/bookings')return json(await booking(db,env,await body(req),false,ctx),201);
  if(m==='GET'&&p==='/api/my-bookings'){const user=await tgIdentity(req.headers.get('x-telegram-init-data'),env);return json(await all(db,"SELECT id,day,start_min,end_min,service_name,price,status FROM bookings WHERE channel='telegram' AND channel_user_id=? AND status='confirmed' AND day>=? ORDER BY day,start_min",user,today()).then(rows=>rows.map(b=>({...b,start:fmt(b.start_min),end:fmt(b.end_min)}))))}
  let match=p.match(/^\/api\/my-bookings\/(\d+)\/(cancel|move)$/);if(m==='POST'&&match){const user=await tgIdentity(req.headers.get('x-telegram-init-data'),env),id=Number(match[1]),b=await one(db,"SELECT * FROM bookings WHERE id=? AND channel='telegram' AND channel_user_id=? AND status='confirmed'",id,user);if(!b)throw new Problem('Запис не знайдено',404);if(match[2]==='move')return json(await move(db,env,id,await body(req),ctx));const result=await db.prepare("UPDATE bookings SET status='cancelled' WHERE id=? AND status='confirmed'").bind(id).run();if(!result.meta.changes)throw new Problem('Запис не знайдено',404);ctx.waitUntil(notify(env,b,'cancelled'));return json(ok())}
  if(!p.startsWith('/api/admin/'))return env.ASSETS.fetch(req);
  await admin(req,env);
  if(m==='GET'&&p==='/api/admin/services')return json(await all(db,'SELECT * FROM services ORDER BY category,id'));
  if(m==='GET'&&p==='/api/admin/categories')return json(await all(db,'SELECT * FROM categories ORDER BY name'));
  if(m==='POST'&&p==='/api/admin/categories'){const x=await body(req),name=required(x.name,'Категорія',80);const r=await db.prepare('INSERT INTO categories(name) VALUES (?) ON CONFLICT(name) DO UPDATE SET active=1').bind(name).run();return json({ok:true,id:r.meta.last_row_id})}
  if(m==='DELETE'&&p.match(/^\/api\/admin\/categories\/\d+$/)){const id=Number(p.split('/').pop());await db.prepare('UPDATE categories SET active=0 WHERE id=?').bind(id).run();return json(ok())}
  if(m==='GET'&&p==='/api/admin/gallery')return json(await all(db,'SELECT * FROM gallery ORDER BY sort_order,id'));
  if(m==='POST'&&p==='/api/admin/gallery'){const x=await body(req),url=required(x.url,'Посилання на фото',1000),caption=String(x.caption||'').trim().slice(0,160),sort=nint(x.sort_order)||0;if(!/^https?:\/\//i.test(url))throw new Problem('Посилання на фото має починатися з http:// або https://');const r=await db.prepare('INSERT INTO gallery(url,caption,sort_order) VALUES (?,?,?)').bind(url,caption,sort).run();return json({id:r.meta.last_row_id})}
  if(m==='DELETE'&&p.match(/^\/api\/admin\/gallery\/\d+$/)){const id=Number(p.split('/').pop());await db.prepare('DELETE FROM gallery WHERE id=?').bind(id).run();return json(ok())}
  if(m==='POST'&&p==='/api/admin/services'){const x=await body(req),category=required(x.category,'Категорія',80),name=required(x.name,'Назва',160),minutes=nint(x.minutes),price=nint(x.price),active=x.active?1:0;if(minutes<5||minutes>720||price<0||price>100000||!Number.isFinite(minutes)||!Number.isFinite(price))throw new Problem('Перевірте ціну та тривалість');await db.prepare('INSERT INTO categories(name) VALUES (?) ON CONFLICT(name) DO UPDATE SET active=1').bind(category).run();if(x.id){const result=await db.prepare('UPDATE services SET category=?,name=?,minutes=?,price=?,active=? WHERE id=?').bind(category,name,minutes,price,active,nint(x.id)).run();if(!result.meta.changes)throw new Problem('Послугу не знайдено',404);return json({id:nint(x.id)})}const r=await db.prepare('INSERT INTO services(category,name,minutes,price,active) VALUES (?,?,?,?,?)').bind(category,name,minutes,price,active).run();return json({id:r.meta.last_row_id})}
  if(m==='GET'&&p==='/api/admin/month'){const month=url.searchParams.get('month');if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month||''))throw new Problem('Оберіть місяць');const from=`${month}-01`,to=plusDays(`${month}-01`,32).slice(0,7)+'-01';return json({openings:await all(db,'SELECT day,COUNT(*) count FROM openings WHERE day>=? AND day<? GROUP BY day',from,to),bookings:await all(db,"SELECT day,COUNT(*) count FROM bookings WHERE day>=? AND day<? AND status='confirmed' GROUP BY day",from,to)})}
  if(m==='GET'&&p==='/api/admin/day'){const d=day(url.searchParams.get('day'),false);return json({openings:(await all(db,'SELECT start_min,end_min FROM openings WHERE day=? ORDER BY start_min',d)).map(x=>({start:fmt(x.start_min),end:fmt(x.end_min)})),bookings:(await all(db,"SELECT * FROM bookings WHERE day=? AND status='confirmed' ORDER BY start_min",d)).map(x=>({...x,start:fmt(x.start_min),end:fmt(x.end_min),contact:x.contact_value||x.phone}))})}
  if(m==='PUT'&&p==='/api/admin/openings'){const x=await body(req),d=day(x.day),intervals=x.intervals;if(!Array.isArray(intervals)||intervals.length>8)throw new Problem('Передайте не більше восьми інтервалів');const ranges=intervals.map(v=>[minute(v.start),minute(v.end)]).sort((a,b)=>a[0]-b[0]);if(ranges.some(([a,b],i)=>a>=b||(i&&ranges[i-1][1]>a)))throw new Problem('Робочі інтервали не повинні перетинатися');const booked=await all(db,"SELECT start_min,end_min FROM bookings WHERE day=? AND status='confirmed'",d);if(booked.some(b=>!ranges.some(([a,z])=>a<=b.start_min&&b.end_min<=z)))throw new Problem('Спершу перенесіть або скасуйте записи поза новими годинами',409);await db.batch([db.prepare('DELETE FROM openings WHERE day=?').bind(d),...ranges.map(([a,z])=>db.prepare('INSERT INTO openings(day,start_min,end_min) VALUES (?,?,?)').bind(d,a,z))]);return json(ranges.map(([a,z])=>({start:fmt(a),end:fmt(z)})))}
  if(m==='POST'&&p==='/api/admin/day-off-24h'){const d=day((await body(req)).day),next=day(plusDays(d,1)),cut=8*60;const booked=await all(db,"SELECT day,start_min,end_min FROM bookings WHERE day IN (?,?) AND status='confirmed'",d,next);if(booked.some(b=>b.day===d?b.end_min>cut:b.start_min<cut))throw new Problem('У цьому проміжку є записи. Спочатку перенесіть або скасуйте їх.',409);const first=await all(db,'SELECT start_min,end_min FROM openings WHERE day=?',d),second=await all(db,'SELECT start_min,end_min FROM openings WHERE day=?',next);const keep=[...first.filter(x=>x.start_min<cut).map(x=>({day:d,start:x.start_min,end:Math.min(x.end_min,cut)})),...second.filter(x=>x.end_min>cut).map(x=>({day:next,start:Math.max(x.start_min,cut),end:x.end_min}))];await db.batch([db.prepare('DELETE FROM openings WHERE day=?').bind(d),db.prepare('DELETE FROM openings WHERE day=?').bind(next),...keep.map(x=>db.prepare('INSERT INTO openings(day,start_min,end_min) VALUES (?,?,?)').bind(x.day,x.start,x.end))]);return json(ok())}
  if(m==='GET'&&p==='/api/admin/bookings'){const history=url.searchParams.get('view')==='history';return json(await all(db,history?"SELECT day,start_min,end_min,service_name,price,client_name,contact_type,contact_value,phone,status FROM bookings WHERE day<? OR status IN ('completed','cancelled') ORDER BY day DESC,start_min DESC LIMIT 300":"SELECT day,start_min,end_min,service_name,price,client_name,contact_type,contact_value,phone,status FROM bookings WHERE day>=? AND status='confirmed' ORDER BY day,start_min LIMIT 300",today()))}
  if(m==='POST'&&p==='/api/admin/bookings')return json(await booking(db,env,await body(req),true,ctx),201);
  if(m==='POST'&&p==='/api/admin/copy-week'){const start=day((await body(req)).day),target=plusDays(start,7);day(plusDays(target,6));const commands=[];for(let i=0;i<7;i++){const from=plusDays(start,i),to=plusDays(target,i);if(await one(db,'SELECT 1 FROM openings WHERE day=? LIMIT 1',to))continue;for(const x of await all(db,'SELECT start_min,end_min FROM openings WHERE day=?',from))commands.push(db.prepare('INSERT INTO openings(day,start_min,end_min) VALUES (?,?,?)').bind(to,x.start_min,x.end_min))}if(commands.length)await db.batch(commands);return json(ok())}
  if(m==='GET'&&p==='/api/admin/clients')return json(await all(db,"SELECT c.id,c.name,c.phone,c.contact_type,c.contact_value,c.note,SUM(CASE WHEN b.status='completed' THEN 1 ELSE 0 END) visits,COALESCE(SUM(CASE WHEN b.status='completed' THEN b.price ELSE 0 END),0) spent,MAX(CASE WHEN b.status='completed' THEN b.day END) last_visit FROM clients c LEFT JOIN bookings b ON b.client_id=c.id GROUP BY c.id ORDER BY c.name"));
  match=p.match(/^\/api\/admin\/clients\/(\d+)(\/note)?$/);if(match){const id=Number(match[1]);if(m==='GET'&&!match[2])return json(await all(db,'SELECT * FROM bookings WHERE client_id=? ORDER BY day DESC',id));if(m==='POST'&&match[2]){const note=(await body(req)).note;if(typeof note!=='string'||note.length>1000)throw new Problem('Нотатка занадто довга');await db.prepare('UPDATE clients SET note=? WHERE id=?').bind(note,id).run();return json(ok())}}
  if(m==='GET'&&p==='/api/admin/stats'){const sources=await all(db,"SELECT source,COUNT(*) count FROM bookings WHERE status!='cancelled' GROUP BY source"),summary=await one(db,"SELECT COUNT(*) bookings,COALESCE(SUM(CASE WHEN status='completed' THEN price ELSE 0 END),0) revenue,COUNT(DISTINCT client_id) clients FROM bookings WHERE status!='cancelled'"),upcoming=await one(db,"SELECT COUNT(*) count FROM bookings WHERE status='confirmed' AND day>=?",today());return json({sources,summary,upcoming:upcoming.count})}
  if(m==='GET'&&p==='/api/admin/settings')return json(await settings(db));
  if(m==='GET'&&p==='/api/admin/calendar-link'){if(!env.CALENDAR_FEED_KEY||env.CALENDAR_FEED_KEY.length<32)throw new Problem('Посилання календаря ще не налаштовано');return json({url:new URL(`/calendar/${env.CALENDAR_FEED_KEY}.ics`,req.url).href})}
  if(m==='POST'&&p==='/api/admin/connect-telegram'){if(!env.TELEGRAM_BOT_TOKEN||!env.TELEGRAM_WEBHOOK_SECRET)throw new Problem('Спочатку додайте ключі Telegram');try{await telegramApi(env,'setWebhook',{url:new URL('/webhooks/telegram',req.url).href,secret_token:env.TELEGRAM_WEBHOOK_SECRET,allowed_updates:['message','callback_query']})}catch(e){console.error(e);throw new Problem('Telegram не вдалося підключити. Перевірте токен бота і webhook secret (лише літери, цифри, _ або -).',502)}return json(ok())}
  if(m==='PUT'&&p==='/api/admin/settings'){const buffer=nint((await body(req)).buffer_minutes);if(![10,15,30].includes(buffer))throw new Problem('Перерва: 10, 15 або 30 хвилин');await db.prepare("UPDATE settings SET value=? WHERE key='buffer_minutes'").bind(String(buffer)).run();return json(ok())}
  if(m==='PUT'&&p==='/api/admin/profile'){const x=await body(req);for(const field of ['address','contact','instagram']){if(typeof x[field]!=='string'||x[field].length>200)throw new Problem('Надто довге поле профілю')}await db.batch(['address','contact','instagram'].map(field=>db.prepare('INSERT INTO settings(key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind(field,x[field].trim())));return json(ok())}
  match=p.match(/^\/api\/admin\/bookings\/(\d+)\/(move|complete|cancel)$/);if(m==='POST'&&match){const id=Number(match[1]);if(match[2]==='move')return json(await move(db,env,id,await body(req),ctx));const b=await one(db,"SELECT * FROM bookings WHERE id=? AND status='confirmed'",id);if(!b)throw new Problem('Запис не знайдено',404);await db.prepare('UPDATE bookings SET status=? WHERE id=? AND status=\'confirmed\'').bind(match[2]==='complete'?'completed':'cancelled',id).run();if(match[2]==='cancel')ctx.waitUntil(notify(env,b,'cancelled'));return json(ok())}
  throw new Problem('Адресу не знайдено',404)
}
async function scheduled(env){const db=env.DB;if(!env.TELEGRAM_BOT_TOKEN)return;const next=await all(db,"SELECT * FROM bookings WHERE status='confirmed' AND channel='telegram' AND day>=? AND day<=?",today(),plusDays(today(),2));for(const b of next){
 const local=new Date(`${b.day}T00:00:00Z`);const dayPart=new Intl.DateTimeFormat('en-US',{timeZone:TZ,timeZoneName:'shortOffset'}).formatToParts(local).find(x=>x.type==='timeZoneName')?.value||'GMT+3';const offset=Number(dayPart.match(/GMT([+-]\d+)/)?.[1]||3);const remaining=(Date.parse(`${b.day}T${fmt(b.start_min)}:00Z`)-offset*3600000-Date.now())/60000;
 for(const [kind,minutes] of [['24h',1440],['2h',120]])if(remaining>minutes-15&&remaining<=minutes){const insert=await db.prepare('INSERT OR IGNORE INTO notifications(booking_id,kind,sent_at) VALUES (?,?,?)').bind(b.id,kind,new Date().toISOString()).run();if(insert.meta.changes)try{await sendTelegram(env,b.channel_user_id,`Нагадуємо про запис 🩷\n${b.day} о ${fmt(b.start_min)}\n${b.service_name}`)}catch{await db.prepare('DELETE FROM notifications WHERE booking_id=? AND kind=?').bind(b.id,kind).run()}}}
 if(env.TELEGRAM_ADMIN_CHAT_ID&&nowMinute()<9*60&&nowMinute()>=8*60+45){const insert=await db.prepare('INSERT OR IGNORE INTO daily_digests(day,sent_at) VALUES (?,?)').bind(today(),new Date().toISOString()).run();if(insert.meta.changes){const visits=await all(db,"SELECT * FROM bookings WHERE day=? AND status='confirmed' ORDER BY start_min",today());try{await sendTelegram(env,env.TELEGRAM_ADMIN_CHAT_ID,`Записи на сьогодні — ${visits.length}\n`+visits.map(x=>`${fmt(x.start_min)} — ${x.client_name}, ${x.service_name}`).join('\n'))}catch{await db.prepare('DELETE FROM daily_digests WHERE day=?').bind(today()).run()}}}}
export default {async fetch(req,env,ctx){try{return await route(req,env,ctx)}catch(e){if(e instanceof Problem)return json({error:e.message},e.status);console.error(e);return json({error:'Внутрішня помилка сервера'},500)}},async scheduled(event,env,ctx){ctx.waitUntil(scheduled(env))}};
