const TZ = 'Europe/Kyiv';
const encoder = new TextEncoder();
class Problem extends Error { constructor(message, status=400) { super(message); this.status=status; } }
const json = (value, status=200) => new Response(JSON.stringify(value), {status, headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}});
const ok = () => ({ok:true});
const one = (db, sql, ...args) => db.prepare(sql).bind(...args).first();
const all = async (db, sql, ...args) => (await db.prepare(sql).bind(...args).all()).results;
const pad = n => String(n).padStart(2,'0');
const fmt = n => `${pad(Math.floor(n/60))}:${pad(n%60)}`;
const today = () => new Intl.DateTimeFormat('sv-SE',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const nowMinute = () => {const parts=new Intl.DateTimeFormat('en-GB',{timeZone:TZ,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date());return Number(parts.find(x=>x.type==='hour').value)*60+Number(parts.find(x=>x.type==='minute').value)};
const plusDays = (day,n) => new Date(Date.parse(day+'T12:00:00Z')+n*86400000).toISOString().slice(0,10);
function day(value, future=true){if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value)||Number.isNaN(Date.parse(value+'T12:00:00Z'))||new Date(value+'T12:00:00Z').toISOString().slice(0,10)!==value)throw new Problem('Невірна дата');if(future&&(value<today()||value>plusDays(today(),90)))throw new Problem('Оберіть дату в межах наступних 90 днів');return value}
function minute(v){if(typeof v!=='string'||!/^([01]\d|2[0-3]):[0-5]\d$/.test(v))throw new Problem('Вкажіть час у форматі ГГ:ХХ');return Number(v.slice(0,2))*60+Number(v.slice(3))}
function required(v,label,max){if(typeof v!=='string'||!v.trim()||v.trim().length>max)throw new Problem(`Перевірте поле «${label}»`);return v.trim()}
const nint = v => Number.isInteger(Number(v)) ? Number(v) : NaN;
const secretEq = (a,b) => {if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0};
const hmac = async (key,data) => new Uint8Array(await crypto.subtle.sign('HMAC',await crypto.subtle.importKey('raw',key,{name:'HMAC',hash:'SHA-256'},false,['sign']),encoder.encode(data)));
const hex = bytes => Array.from(bytes).map(x=>x.toString(16).padStart(2,'0')).join('');
const icsText = v => String(v).replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');
function calendarFeed(bookings){const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Online Zapys//Booking Calendar//UK','CALSCALE:GREGORIAN','X-WR-CALNAME:Мої записи','X-WR-TIMEZONE:Europe/Kyiv'];for(const b of bookings){const stamp=b.day.replaceAll('-',''),at=n=>`${stamp}T${pad(Math.floor(n/60))}${pad(n%60)}00`;lines.push('BEGIN:VEVENT',`UID:booking-${b.id}@online-zapys`,`DTSTAMP:${new Date(b.created_at).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}`,`DTSTART;TZID=Europe/Kyiv:${at(b.start_min)}`,`DTEND;TZID=Europe/Kyiv:${at(b.end_min)}`,`SUMMARY:${icsText(b.service_name)}`,'END:VEVENT')}lines.push('END:VCALENDAR');return lines.join('\r\n')+'\r\n'}
async function tgIdentity(raw,env){if(!env.TELEGRAM_BOT_TOKEN||!raw||raw.length>4096)throw new Problem('Немає даних Telegram',401);const p=new URLSearchParams(raw),signature=p.get('hash');p.delete('hash');const check=[...p.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join('\n');const key=await hmac(encoder.encode('WebAppData'),env.TELEGRAM_BOT_TOKEN);if(!secretEq(signature,hex(await hmac(key,check))))throw new Problem('Неправильний підпис Telegram',401);let u;try{u=JSON.parse(p.get('user'));if(!Number.isInteger(Number(u.id))||Math.abs(Date.now()/1000-Number(p.get('auth_date')))>86400)throw Error()}catch{throw new Problem('Сесія Telegram застаріла',401)}return String(u.id)}
async function admin(req,env){if(env.BOOKING_ADMIN_KEY?.length<16)throw new Problem('Адмінключ не налаштований',500);if(secretEq(req.headers.get('x-admin-key'),env.BOOKING_ADMIN_KEY))return;try{if(env.ADMIN_TELEGRAM_ID&&await tgIdentity(req.headers.get('x-telegram-init-data'),env)===env.ADMIN_TELEGRAM_ID)return}catch{}throw new Problem('Потрібен доступ майстра',403)}
async function body(req){let str=await req.text();if(str.length>16384)throw new Problem('Завеликий запит');try{const v=JSON.parse(str);if(v&&typeof v==='object'&&!Array.isArray(v))return v}catch{}throw new Problem('Некоректні дані запиту')}
async function settings(db){return Object.fromEntries((await all(db,'SELECT key,value FROM settings')).map(x=>[x.key,x.value]))}
async function available(db,d,duration,exclude=-1){const [windows,bookings,setting]=await Promise.all([all(db,'SELECT start_min,end_min FROM openings WHERE day=? ORDER BY start_min',d),all(db,"SELECT id,start_min,end_min FROM bookings WHERE day=? AND status='confirmed' AND id!=?",d,exclude),one(db,"SELECT value FROM settings WHERE key='buffer_minutes'")]);const buffer=Number(setting?.value||10),out=new Set();for(const w of windows){for(let pos=Math.ceil(w.start_min/5)*5;pos+duration<=w.end_min;pos+=5){if(d===today()&&pos<=nowMinute())continue;if(bookings.every(b=>pos>=b.end_min+buffer||pos+duration+buffer<=b.start_min))out.add(fmt(pos))}}return [...out].sort()}
async function sendTelegram(env,recipient,text,webApp){if(!env.TELEGRAM_BOT_TOKEN)return;let message={chat_id:recipient,text};if(webApp)message.reply_markup={inline_keyboard:[[{text:'📅 Записатися',web_app:{url:webApp}}]]};const response=await fetch(`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/sendMessage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(message)});if(!response.ok)throw Error('Telegram send failed')}
async function notify(env,b,kind){if(b?.channel==='telegram'&&b.channel_user_id)await sendTelegram(env,b.channel_user_id,`${{created:'Ваш запис підтверджено',moved:'Ваш запис перенесено',cancelled:'Ваш запис скасовано'}[kind]} 💜\n${b.day} о ${fmt(b.start_min)}\n${b.service_name}`)}
async function booking(db,env,data,manual,ctx){const d=day(data.day),start=minute(data.time),id=nint(data.service_id);let name=required(data.name,'Ім’я',80),phone=required(data.phone,'Телефон',30);if(!/^\+?[0-9 ()-]{9,30}$/.test(phone))throw new Problem('Перевірте номер телефону');const service=await one(db,'SELECT * FROM services WHERE id=? AND active=1',id);if(!service)throw new Problem('Послуга вже недоступна',409);let channel=null,user=null;if(!manual&&data.telegram_init_data){user=await tgIdentity(data.telegram_init_data,env);channel='telegram'}let source=manual?'manual':channel||data.source;if(!['web','telegram','instagram','viber','manual'].includes(source))source='web';
  if(start%5||d===today()&&start<=nowMinute())throw new Problem('Оберіть доступний час',409);
  // The availability and overlap checks belong to one atomic INSERT statement.
  await db.prepare('INSERT INTO clients(phone,name) VALUES (?,?) ON CONFLICT(phone) DO UPDATE SET name=excluded.name').bind(phone,name).run();
  const client=await one(db,'SELECT id FROM clients WHERE phone=?',phone);const buffer=Number((await one(db,"SELECT value FROM settings WHERE key='buffer_minutes'"))?.value||10);
  const result=await db.prepare(`INSERT INTO bookings(day,start_min,end_min,service_id,service_name,price,client_name,phone,source,created_at,client_id,channel,channel_user_id)
  SELECT ?,?,?,?,?,?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM openings WHERE day=? AND start_min<=? AND end_min>=?)
  AND NOT EXISTS(SELECT 1 FROM bookings WHERE day=? AND status='confirmed' AND NOT (? >= end_min+? OR ?+?+? <= start_min))`).bind(d,start,start+service.minutes,id,service.name,service.price,name,phone,source,new Date().toISOString(),client.id,channel,user,d,start,start+service.minutes,d,start,buffer,start,service.minutes,buffer).run();
  if(!result.meta.changes)throw new Problem('Цей час уже зайнятий або недоступний. Оберіть інший.',409);
  const b=await one(db,'SELECT * FROM bookings WHERE id=?',result.meta.last_row_id);if(channel)ctx.waitUntil(notify(env,b,'created'));return {id:b.id,day:d,start:fmt(start),end:fmt(b.end_min),service:b.service_name,price:b.price}}
async function move(db,env,id,data,ctx){const d=day(data.day),start=minute(data.time);if(start%5||d===today()&&start<=nowMinute())throw new Problem('Оберіть доступний час',409);const b=await one(db,"SELECT * FROM bookings WHERE id=? AND status='confirmed'",id);if(!b)throw new Problem('Запис не знайдено',404);const duration=b.end_min-b.start_min,buffer=Number((await one(db,"SELECT value FROM settings WHERE key='buffer_minutes'"))?.value||10);const result=await db.prepare(`UPDATE bookings SET day=?,start_min=?,end_min=? WHERE id=? AND status='confirmed'
 AND EXISTS(SELECT 1 FROM openings WHERE day=? AND start_min<=? AND end_min>=?)
 AND NOT EXISTS(SELECT 1 FROM bookings other WHERE other.day=? AND other.status='confirmed' AND other.id!=? AND NOT (? >= other.end_min+? OR ?+?+?<=other.start_min))`).bind(d,start,start+duration,id,d,start,start+duration,d,id,start,buffer,start,duration,buffer).run();if(!result.meta.changes)throw new Problem('Новий час зайнятий або недоступний',409);await db.prepare('DELETE FROM notifications WHERE booking_id=?').bind(id).run();ctx.waitUntil(notify(env,{...b,day:d,start_min:start},'moved'));return {ok:true,day:d,start:fmt(start)}}
async function route(req,env,ctx){const db=env.DB;if(!db)throw new Problem('База даних не підключена',500);const url=new URL(req.url),p=url.pathname,m=req.method;
  if(m==='GET'&&p.startsWith('/calendar/')){if(!env.CALENDAR_FEED_KEY||env.CALENDAR_FEED_KEY.length<32||!secretEq(p.slice('/calendar/'.length),env.CALENDAR_FEED_KEY+'.ics'))throw new Problem('Адресу не знайдено',404);const bookings=await all(db,"SELECT id,day,start_min,end_min,service_name,created_at FROM bookings WHERE status='confirmed' AND day>=? AND day<=? ORDER BY day,start_min",plusDays(today(),-30),plusDays(today(),365));return new Response(calendarFeed(bookings),{headers:{'content-type':'text/calendar; charset=utf-8','cache-control':'private, max-age=300','x-content-type-options':'nosniff'}})}
  if(m==='POST'&&p==='/webhooks/telegram'){if(!env.TELEGRAM_WEBHOOK_SECRET||!secretEq(req.headers.get('x-telegram-bot-api-secret-token'),env.TELEGRAM_WEBHOOK_SECRET))throw new Problem('Заборонено',403);const update=await body(req),message=update.message;if(message?.chat?.type==='private')ctx.waitUntil(sendTelegram(env,message.chat.id,'Вітаємо! Оберіть послугу, дату й час у застосунку запису 💜',new URL('/?source=telegram',req.url).href));return json(ok())}
  if(m==='GET'&&p==='/api/services')return json(await all(db,'SELECT * FROM services WHERE active=1 ORDER BY category,id'));
  if(m==='GET'&&p==='/api/public-info')return json(await settings(db));
  if(m==='GET'&&p==='/api/days'){const from=today(),to=plusDays(from,90);return json((await all(db,'SELECT DISTINCT day FROM openings WHERE day>=? AND day<=? ORDER BY day',from,to)).map(x=>x.day))}
  if(m==='GET'&&p==='/api/slots'){const d=day(url.searchParams.get('day')),s=await one(db,'SELECT minutes FROM services WHERE id=? AND active=1',nint(url.searchParams.get('service_id')));if(!s)throw new Problem('Оберіть послугу');return json(await available(db,d,s.minutes))}
  if(m==='POST'&&p==='/api/bookings')return json(await booking(db,env,await body(req),false,ctx),201);
  if(m==='GET'&&p==='/api/my-bookings'){const user=await tgIdentity(req.headers.get('x-telegram-init-data'),env);return json(await all(db,"SELECT id,day,start_min,end_min,service_name,price,status FROM bookings WHERE channel='telegram' AND channel_user_id=? AND status='confirmed' AND day>=? ORDER BY day,start_min",user,today()).then(rows=>rows.map(b=>({...b,start:fmt(b.start_min),end:fmt(b.end_min)}))))}
  let match=p.match(/^\/api\/my-bookings\/(\d+)\/(cancel|move)$/);if(m==='POST'&&match){const user=await tgIdentity(req.headers.get('x-telegram-init-data'),env),id=Number(match[1]),b=await one(db,"SELECT * FROM bookings WHERE id=? AND channel='telegram' AND channel_user_id=? AND status='confirmed'",id,user);if(!b)throw new Problem('Запис не знайдено',404);if(match[2]==='move')return json(await move(db,env,id,await body(req),ctx));const result=await db.prepare("UPDATE bookings SET status='cancelled' WHERE id=? AND status='confirmed'").bind(id).run();if(!result.meta.changes)throw new Problem('Запис не знайдено',404);ctx.waitUntil(notify(env,b,'cancelled'));return json(ok())}
  if(!p.startsWith('/api/admin/'))return env.ASSETS.fetch(req);
  await admin(req,env);
  if(m==='GET'&&p==='/api/admin/services')return json(await all(db,'SELECT * FROM services ORDER BY category,id'));
  if(m==='POST'&&p==='/api/admin/services'){const x=await body(req),category=required(x.category,'Категорія',80),name=required(x.name,'Назва',160),minutes=nint(x.minutes),price=nint(x.price),active=x.active?1:0;if(minutes<5||minutes>720||price<0||price>100000||!Number.isFinite(minutes)||!Number.isFinite(price))throw new Problem('Перевірте ціну та тривалість');if(x.id){const result=await db.prepare('UPDATE services SET category=?,name=?,minutes=?,price=?,active=? WHERE id=?').bind(category,name,minutes,price,active,nint(x.id)).run();if(!result.meta.changes)throw new Problem('Послугу не знайдено',404);return json({id:nint(x.id)})}const r=await db.prepare('INSERT INTO services(category,name,minutes,price,active) VALUES (?,?,?,?,?)').bind(category,name,minutes,price,active).run();return json({id:r.meta.last_row_id})}
  if(m==='GET'&&p==='/api/admin/day'){const d=day(url.searchParams.get('day'),false);return json({openings:(await all(db,'SELECT start_min,end_min FROM openings WHERE day=? ORDER BY start_min',d)).map(x=>({start:fmt(x.start_min),end:fmt(x.end_min)})),bookings:(await all(db,"SELECT * FROM bookings WHERE day=? AND status='confirmed' ORDER BY start_min",d)).map(x=>({...x,start:fmt(x.start_min),end:fmt(x.end_min)}))})}
  if(m==='PUT'&&p==='/api/admin/openings'){const x=await body(req),d=day(x.day),intervals=x.intervals;if(!Array.isArray(intervals)||intervals.length>8)throw new Problem('Передайте не більше восьми інтервалів');const ranges=intervals.map(v=>[minute(v.start),minute(v.end)]).sort((a,b)=>a[0]-b[0]);if(ranges.some(([a,b],i)=>a>=b||(i&&ranges[i-1][1]>a)))throw new Problem('Робочі інтервали не повинні перетинатися');const booked=await all(db,"SELECT start_min,end_min FROM bookings WHERE day=? AND status='confirmed'",d);if(booked.some(b=>!ranges.some(([a,z])=>a<=b.start_min&&b.end_min<=z)))throw new Problem('Спершу перенесіть або скасуйте записи поза новими годинами',409);await db.batch([db.prepare('DELETE FROM openings WHERE day=?').bind(d),...ranges.map(([a,z])=>db.prepare('INSERT INTO openings(day,start_min,end_min) VALUES (?,?,?)').bind(d,a,z))]);return json(ranges.map(([a,z])=>({start:fmt(a),end:fmt(z)})))}
  if(m==='POST'&&p==='/api/admin/bookings')return json(await booking(db,env,await body(req),true,ctx),201);
  if(m==='POST'&&p==='/api/admin/copy-week'){const start=day((await body(req)).day),target=plusDays(start,7);day(plusDays(target,6));const commands=[];for(let i=0;i<7;i++){const from=plusDays(start,i),to=plusDays(target,i);if(await one(db,'SELECT 1 FROM openings WHERE day=? LIMIT 1',to))continue;for(const x of await all(db,'SELECT start_min,end_min FROM openings WHERE day=?',from))commands.push(db.prepare('INSERT INTO openings(day,start_min,end_min) VALUES (?,?,?)').bind(to,x.start_min,x.end_min))}if(commands.length)await db.batch(commands);return json(ok())}
  if(m==='GET'&&p==='/api/admin/clients')return json(await all(db,"SELECT c.id,c.name,c.phone,c.note,SUM(CASE WHEN b.status='completed' THEN 1 ELSE 0 END) visits,COALESCE(SUM(CASE WHEN b.status='completed' THEN b.price ELSE 0 END),0) spent,MAX(CASE WHEN b.status='completed' THEN b.day END) last_visit FROM clients c LEFT JOIN bookings b ON b.client_id=c.id GROUP BY c.id ORDER BY c.name"));
  match=p.match(/^\/api\/admin\/clients\/(\d+)(\/note)?$/);if(match){const id=Number(match[1]);if(m==='GET'&&!match[2])return json(await all(db,'SELECT * FROM bookings WHERE client_id=? ORDER BY day DESC',id));if(m==='POST'&&match[2]){const note=(await body(req)).note;if(typeof note!=='string'||note.length>1000)throw new Problem('Нотатка занадто довга');await db.prepare('UPDATE clients SET note=? WHERE id=?').bind(note,id).run();return json(ok())}}
  if(m==='GET'&&p==='/api/admin/stats'){const sources=await all(db,"SELECT source,COUNT(*) count FROM bookings WHERE status!='cancelled' GROUP BY source"),summary=await one(db,"SELECT COUNT(*) bookings,COALESCE(SUM(CASE WHEN status='completed' THEN price ELSE 0 END),0) revenue,COUNT(DISTINCT client_id) clients FROM bookings WHERE status!='cancelled'"),upcoming=await one(db,"SELECT COUNT(*) count FROM bookings WHERE status='confirmed' AND day>=?",today());return json({sources,summary,upcoming:upcoming.count})}
  if(m==='GET'&&p==='/api/admin/settings')return json(await settings(db));
  if(m==='GET'&&p==='/api/admin/calendar-link'){if(!env.CALENDAR_FEED_KEY||env.CALENDAR_FEED_KEY.length<32)throw new Problem('Посилання календаря ще не налаштовано');return json({url:new URL(`/calendar/${env.CALENDAR_FEED_KEY}.ics`,req.url).href})}
  if(m==='POST'&&p==='/api/admin/connect-telegram'){if(!env.TELEGRAM_BOT_TOKEN||!env.TELEGRAM_WEBHOOK_SECRET)throw new Problem('Спочатку додайте ключі Telegram');const u=`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/setWebhook`;const response=await fetch(u,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url:new URL('/webhooks/telegram',req.url).href,secret_token:env.TELEGRAM_WEBHOOK_SECRET,allowed_updates:['message']})});const result=await response.json();if(!result.ok)throw new Problem('Telegram не вдалося підключити',502);return json(ok())}
  if(m==='PUT'&&p==='/api/admin/settings'){const buffer=nint((await body(req)).buffer_minutes);if(![10,15,30].includes(buffer))throw new Problem('Перерва: 10, 15 або 30 хвилин');await db.prepare("UPDATE settings SET value=? WHERE key='buffer_minutes'").bind(String(buffer)).run();return json(ok())}
  if(m==='PUT'&&p==='/api/admin/profile'){const x=await body(req);for(const field of ['address','contact']){if(typeof x[field]!=='string'||x[field].length>200)throw new Problem('Надто довге поле профілю')}await db.batch(['address','contact'].map(field=>db.prepare('UPDATE settings SET value=? WHERE key=?').bind(x[field].trim(),field)));return json(ok())}
  match=p.match(/^\/api\/admin\/bookings\/(\d+)\/(move|complete|cancel)$/);if(m==='POST'&&match){const id=Number(match[1]);if(match[2]==='move')return json(await move(db,env,id,await body(req),ctx));const b=await one(db,"SELECT * FROM bookings WHERE id=? AND status='confirmed'",id);if(!b)throw new Problem('Запис не знайдено',404);await db.prepare('UPDATE bookings SET status=? WHERE id=? AND status=\'confirmed\'').bind(match[2]==='complete'?'completed':'cancelled',id).run();if(match[2]==='cancel')ctx.waitUntil(notify(env,b,'cancelled'));return json(ok())}
  throw new Problem('Адресу не знайдено',404)
}
async function scheduled(env){const db=env.DB;if(!env.TELEGRAM_BOT_TOKEN)return;const next=await all(db,"SELECT * FROM bookings WHERE status='confirmed' AND channel='telegram' AND day>=? AND day<=?",today(),plusDays(today(),2));for(const b of next){
 const local=new Date(`${b.day}T00:00:00Z`);const dayPart=new Intl.DateTimeFormat('en-US',{timeZone:TZ,timeZoneName:'shortOffset'}).formatToParts(local).find(x=>x.type==='timeZoneName')?.value||'GMT+3';const offset=Number(dayPart.match(/GMT([+-]\d+)/)?.[1]||3);const remaining=(Date.parse(`${b.day}T${fmt(b.start_min)}:00Z`)-offset*3600000-Date.now())/60000;
 for(const [kind,minutes] of [['24h',1440],['2h',120]])if(remaining>minutes-15&&remaining<=minutes){const insert=await db.prepare('INSERT OR IGNORE INTO notifications(booking_id,kind,sent_at) VALUES (?,?,?)').bind(b.id,kind,new Date().toISOString()).run();if(insert.meta.changes)try{await sendTelegram(env,b.channel_user_id,`Нагадуємо про запис 💜\n${b.day} о ${fmt(b.start_min)}\n${b.service_name}`)}catch{await db.prepare('DELETE FROM notifications WHERE booking_id=? AND kind=?').bind(b.id,kind).run()}}}
 if(env.TELEGRAM_ADMIN_CHAT_ID&&nowMinute()<9*60&&nowMinute()>=8*60+45){const insert=await db.prepare('INSERT OR IGNORE INTO daily_digests(day,sent_at) VALUES (?,?)').bind(today(),new Date().toISOString()).run();if(insert.meta.changes){const visits=await all(db,"SELECT * FROM bookings WHERE day=? AND status='confirmed' ORDER BY start_min",today());try{await sendTelegram(env,env.TELEGRAM_ADMIN_CHAT_ID,`Записи на сьогодні — ${visits.length}\n`+visits.map(x=>`${fmt(x.start_min)} — ${x.client_name}, ${x.service_name}`).join('\n'))}catch{await db.prepare('DELETE FROM daily_digests WHERE day=?').bind(today()).run()}}}}
export default {async fetch(req,env,ctx){try{return await route(req,env,ctx)}catch(e){if(e instanceof Problem)return json({error:e.message},e.status);console.error(e);return json({error:'Внутрішня помилка сервера'},500)}},async scheduled(event,env,ctx){ctx.waitUntil(scheduled(env))}};
